### Feedforward Neural Networks

In [67]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.autograd import Variable

In [68]:
train_dataset = dsets.MNIST(root='./MNIST',train=True,transform=transforms.ToTensor(),download=True)

test_dataset = dsets.MNIST(root='./MNIST',train=False,transform=transforms.ToTensor())

In [69]:
#### Make Dataset Iterable

batch_size=100

n_iters = 3000

num_epochs = (n_iters*batch_size)/len(train_dataset)
num_epochs = int(num_epochs)
num_epochs

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,batch_size=batch_size,shuffle=False)

In [70]:
#### Building Model -- 1 Hidden Layer

class FeedForwardNeuralNetModel1(nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(FeedForwardNeuralNetModel1,self).__init__()
        #Linear function
        self.fc1 = nn.Linear(input_dim,hidden_dim)
        
        #Non-linearity --- Sigmoid
        #self.sigmoid = nn.Sigmoid()
        
        #Non-linearity --- Tanh
        #self.tanh = nn.Tanh()
        
        #Non-linearity --- Relu
        self.relu=nn.ReLU()
        
        #Linear function(Readout)
        self.fc2 = nn.Linear(hidden_dim,output_dim)

    def forward(self,x):
        #Linear function
        out=self.fc1(x)
        #Non-linearity
        out=self.relu(out)
        #Linear function(Readout)
        out=self.fc2(out)
        return out

In [71]:
#### Building Model -- 2 Hidden Layer

class FeedForwardNeuralNetModel2(nn.Module):
    def __init__(self,input_dim,hidden_size,num_classes):
        super(FeedForwardNeuralNetModel2,self).__init__()
        #Linear function 1
        self.fc1 = nn.Linear(input_dim,hidden_dim)
        #Non-linearity 1
        self.relu1 = nn.ReLU()
        #Linear function 2
        self.fc2 = nn.Linear(hidden_dim,hidden_dim)
        #Non-linearity 2
        self.relu2=nn.ReLU()
        
        #Linear function 3 (Readout)
        self.fc3 = nn.Linear(hidden_dim,output_dim)

    def forward(self,x):
        #Linear function 1
        out=self.fc1(x)
        #Non-linearity 1
        out=self.relu1(out)
        #Linear function 2
        out=self.fc2(out)
        #Non-linearity 2
        out=self.relu2(out)
        #Linear function 3 (Readout)
        out=self.fc3(out)
        return out

In [72]:
#### Instantiate the Model

input_dim = 28*28
hidden_dim=100
output_dim = 10

model = FeedForwardNeuralNetModel2(input_dim,hidden_dim,output_dim)
model.cuda()

FeedForwardNeuralNetModel2(
  (fc1): Linear(in_features=784, out_features=100, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=100, out_features=100, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=100, out_features=10, bias=True)
)

In [73]:
#### Instantiate Loss Class

criterion = nn.CrossEntropyLoss()

In [74]:
#### Instantiate Optimizer Class


learning_rate = 0.1
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [75]:
#### Parameters in-depth

print(model.parameters())
print(len(list(model.parameters())))

#FC 1 Parameters
print(list(model.parameters())[0].size())

#FC 1 Biase Parameters
print(list(model.parameters())[1].size())

#FC 2 Parameters
print(list(model.parameters())[2].size())

#FC 2 Bias Parameters
print(list(model.parameters())[3].size())

<generator object Module.parameters at 0x00000144652D36D0>
6
torch.Size([100, 784])
torch.Size([100])
torch.Size([100, 100])
torch.Size([100])


In [76]:
print(len(train_loader))
for (images,labels) in train_loader:
    print(labels)

600
tensor([4, 1, 5, 2, 5, 8, 1, 2, 6, 9, 2, 1, 2, 6, 8, 9, 0, 9, 2, 2, 8, 7, 8, 7,
        3, 7, 8, 7, 9, 9, 9, 4, 4, 8, 5, 9, 7, 9, 8, 1, 6, 2, 6, 4, 6, 7, 8, 9,
        1, 0, 4, 3, 2, 6, 4, 8, 8, 0, 6, 1, 0, 3, 1, 1, 9, 5, 9, 2, 0, 7, 2, 1,
        5, 0, 4, 3, 5, 9, 7, 1, 8, 7, 2, 0, 3, 7, 6, 8, 3, 9, 4, 8, 1, 7, 5, 4,
        4, 8, 6, 2])
tensor([1, 7, 7, 4, 0, 8, 6, 6, 5, 4, 8, 9, 5, 5, 0, 1, 3, 6, 9, 6, 9, 1, 7, 4,
        4, 8, 9, 7, 5, 2, 0, 2, 1, 1, 2, 2, 3, 6, 3, 2, 8, 7, 9, 8, 2, 2, 6, 8,
        6, 1, 2, 8, 4, 5, 0, 9, 7, 5, 4, 0, 7, 3, 1, 5, 8, 4, 2, 9, 1, 6, 5, 9,
        9, 2, 0, 7, 3, 4, 3, 1, 1, 1, 6, 7, 1, 7, 9, 0, 4, 6, 7, 1, 5, 9, 8, 7,
        5, 2, 9, 2])
tensor([7, 1, 6, 7, 9, 1, 0, 2, 2, 8, 7, 7, 3, 1, 7, 8, 6, 1, 3, 3, 7, 4, 4, 3,
        1, 1, 2, 6, 3, 7, 7, 3, 1, 6, 8, 0, 6, 6, 4, 1, 5, 3, 2, 9, 1, 6, 1, 9,
        7, 5, 3, 1, 7, 1, 1, 4, 0, 0, 5, 3, 0, 6, 9, 9, 1, 8, 6, 7, 6, 3, 5, 1,
        3, 1, 1, 1, 6, 2, 0, 4, 6, 1, 4, 3, 1, 6, 5, 1, 0, 8, 1, 7, 0, 6, 

        5, 2, 9, 9])
tensor([5, 6, 1, 4, 2, 5, 8, 1, 3, 9, 2, 5, 7, 7, 8, 4, 3, 2, 8, 7, 4, 9, 2, 7,
        0, 3, 0, 3, 5, 7, 4, 3, 8, 9, 5, 9, 0, 7, 0, 6, 6, 9, 5, 2, 2, 9, 8, 0,
        1, 4, 0, 4, 1, 0, 9, 1, 5, 1, 1, 7, 4, 4, 0, 9, 2, 5, 8, 3, 1, 9, 4, 1,
        0, 1, 0, 3, 6, 1, 4, 9, 7, 8, 3, 3, 0, 0, 0, 7, 3, 0, 2, 4, 3, 4, 2, 7,
        3, 1, 0, 4])
tensor([4, 8, 0, 1, 7, 1, 5, 2, 3, 6, 9, 7, 4, 6, 7, 2, 9, 4, 7, 1, 4, 9, 8, 5,
        5, 6, 2, 2, 9, 6, 5, 8, 3, 8, 3, 3, 5, 4, 6, 9, 6, 0, 6, 0, 2, 7, 4, 7,
        5, 7, 4, 2, 9, 2, 8, 8, 5, 6, 0, 4, 2, 8, 2, 5, 0, 4, 7, 0, 4, 8, 5, 1,
        4, 2, 5, 0, 2, 8, 4, 6, 2, 2, 7, 7, 1, 5, 7, 1, 0, 9, 8, 8, 9, 1, 4, 7,
        0, 3, 5, 3])
tensor([0, 5, 0, 4, 6, 9, 8, 1, 0, 4, 7, 9, 9, 6, 0, 7, 1, 6, 1, 5, 5, 4, 8, 1,
        1, 1, 4, 1, 0, 6, 8, 7, 6, 2, 9, 9, 2, 6, 0, 9, 5, 0, 7, 2, 8, 5, 0, 8,
        6, 3, 7, 2, 9, 5, 5, 9, 3, 7, 4, 9, 5, 6, 0, 6, 0, 1, 9, 6, 3, 4, 9, 3,
        7, 9, 1, 9, 0, 0, 8, 8, 1, 4, 7, 5, 1, 8, 8, 5, 8

tensor([8, 6, 8, 7, 8, 6, 9, 1, 9, 3, 8, 4, 1, 8, 5, 3, 0, 8, 9, 8, 2, 1, 8, 5,
        4, 4, 4, 1, 4, 0, 2, 5, 7, 0, 6, 2, 5, 6, 8, 3, 3, 1, 9, 7, 8, 2, 5, 1,
        3, 2, 7, 5, 5, 6, 1, 3, 3, 7, 7, 1, 2, 5, 0, 6, 1, 4, 4, 8, 2, 6, 9, 7,
        1, 9, 3, 7, 7, 8, 9, 5, 2, 1, 9, 1, 3, 1, 0, 8, 1, 2, 4, 6, 3, 0, 9, 3,
        8, 1, 7, 3])
tensor([4, 2, 3, 1, 8, 3, 2, 1, 7, 0, 4, 5, 8, 6, 4, 9, 8, 7, 1, 9, 4, 2, 7, 9,
        9, 0, 9, 9, 1, 5, 0, 4, 7, 0, 4, 3, 4, 2, 7, 9, 9, 3, 7, 4, 0, 1, 5, 3,
        3, 5, 0, 7, 9, 5, 0, 3, 5, 9, 8, 3, 6, 7, 1, 2, 8, 8, 1, 3, 0, 8, 0, 3,
        0, 5, 8, 2, 0, 0, 6, 3, 3, 8, 3, 7, 9, 9, 7, 2, 9, 3, 8, 7, 4, 4, 9, 6,
        5, 3, 4, 3])
tensor([6, 4, 6, 2, 4, 4, 5, 7, 8, 6, 6, 4, 8, 0, 3, 6, 7, 3, 2, 7, 9, 2, 4, 3,
        5, 7, 6, 1, 9, 0, 7, 1, 9, 7, 6, 9, 4, 6, 5, 0, 2, 1, 9, 9, 3, 9, 0, 6,
        3, 5, 4, 6, 1, 1, 0, 9, 6, 1, 3, 2, 4, 0, 3, 4, 3, 4, 7, 0, 4, 1, 7, 7,
        4, 6, 1, 7, 1, 9, 7, 7, 3, 0, 1, 0, 0, 2, 0, 2, 5, 1, 8, 8, 8, 8, 9, 4

tensor([1, 0, 6, 0, 9, 6, 4, 2, 4, 7, 8, 7, 0, 0, 1, 3, 4, 5, 9, 9, 4, 3, 5, 5,
        9, 0, 0, 7, 2, 7, 6, 7, 7, 8, 1, 1, 3, 8, 9, 7, 0, 9, 0, 0, 7, 0, 4, 9,
        0, 5, 2, 2, 9, 0, 5, 9, 7, 8, 5, 7, 5, 1, 2, 1, 9, 5, 9, 8, 4, 3, 7, 5,
        3, 4, 3, 2, 0, 0, 6, 1, 7, 9, 9, 6, 2, 2, 1, 7, 4, 0, 2, 1, 0, 3, 0, 9,
        2, 4, 3, 8])
tensor([5, 4, 8, 8, 6, 3, 9, 7, 1, 6, 9, 7, 7, 1, 7, 0, 8, 8, 4, 1, 9, 5, 0, 9,
        1, 7, 4, 8, 3, 3, 3, 7, 1, 4, 7, 5, 0, 2, 9, 1, 0, 8, 0, 8, 1, 5, 2, 1,
        0, 2, 0, 2, 2, 3, 7, 9, 6, 2, 9, 8, 9, 9, 6, 8, 1, 8, 0, 9, 9, 7, 4, 4,
        0, 7, 2, 7, 9, 7, 0, 8, 9, 5, 1, 6, 7, 7, 6, 9, 8, 3, 6, 4, 8, 7, 7, 3,
        6, 9, 4, 7])
tensor([0, 3, 8, 6, 9, 8, 2, 6, 5, 8, 0, 9, 3, 0, 6, 5, 5, 8, 0, 9, 1, 3, 3, 1,
        4, 6, 3, 1, 6, 5, 7, 1, 8, 9, 9, 7, 9, 7, 2, 9, 9, 0, 9, 8, 7, 6, 3, 8,
        8, 8, 7, 8, 3, 4, 6, 4, 7, 4, 9, 4, 0, 2, 1, 2, 0, 6, 7, 6, 0, 9, 3, 6,
        3, 4, 0, 2, 9, 5, 1, 9, 6, 9, 9, 8, 7, 1, 0, 6, 6, 9, 0, 9, 6, 8, 2, 5

tensor([0, 9, 3, 1, 1, 3, 4, 9, 0, 0, 3, 9, 2, 0, 4, 7, 3, 2, 8, 6, 7, 9, 8, 2,
        5, 1, 8, 4, 9, 9, 8, 3, 6, 0, 3, 6, 9, 0, 6, 7, 4, 0, 5, 2, 7, 0, 4, 8,
        5, 6, 8, 0, 8, 2, 5, 2, 0, 8, 9, 5, 6, 8, 1, 9, 9, 8, 1, 6, 1, 5, 2, 8,
        3, 7, 5, 9, 0, 6, 2, 3, 4, 2, 4, 1, 9, 7, 1, 9, 7, 0, 0, 2, 6, 7, 0, 2,
        2, 0, 9, 5])
tensor([3, 8, 7, 5, 4, 4, 8, 6, 6, 1, 2, 2, 1, 8, 7, 3, 7, 5, 3, 5, 7, 6, 1, 9,
        9, 4, 9, 6, 9, 5, 3, 2, 2, 4, 7, 3, 8, 0, 0, 9, 9, 1, 1, 7, 5, 0, 9, 2,
        3, 5, 8, 5, 4, 0, 8, 8, 5, 1, 9, 0, 4, 1, 4, 7, 4, 0, 8, 0, 9, 1, 3, 9,
        1, 7, 1, 8, 0, 1, 5, 1, 2, 3, 4, 0, 0, 6, 2, 8, 2, 4, 7, 5, 9, 2, 4, 2,
        2, 3, 7, 4])
tensor([8, 2, 4, 1, 8, 2, 3, 1, 9, 7, 9, 2, 5, 7, 4, 0, 0, 8, 1, 9, 2, 3, 5, 2,
        7, 1, 1, 9, 7, 3, 1, 6, 3, 3, 6, 8, 7, 0, 4, 0, 7, 7, 4, 6, 2, 3, 6, 0,
        3, 7, 3, 5, 6, 4, 6, 5, 5, 6, 6, 7, 3, 0, 1, 9, 9, 3, 6, 8, 8, 1, 9, 1,
        7, 4, 0, 5, 3, 0, 1, 5, 2, 8, 2, 8, 4, 8, 1, 0, 0, 8, 2, 0, 1, 1, 5, 0

tensor([1, 6, 2, 7, 3, 5, 1, 3, 8, 5, 4, 4, 2, 0, 0, 1, 3, 9, 7, 5, 9, 2, 9, 6,
        1, 2, 5, 0, 9, 0, 5, 3, 6, 5, 4, 5, 9, 5, 7, 2, 1, 4, 8, 5, 9, 7, 4, 0,
        1, 9, 9, 2, 8, 1, 1, 6, 9, 7, 7, 8, 8, 0, 3, 7, 2, 1, 6, 1, 1, 0, 2, 1,
        5, 1, 1, 8, 8, 8, 4, 0, 4, 9, 1, 6, 7, 3, 2, 9, 8, 7, 5, 6, 2, 1, 3, 3,
        1, 8, 8, 1])
tensor([7, 4, 5, 5, 4, 4, 8, 0, 2, 4, 6, 6, 9, 1, 9, 2, 8, 1, 2, 2, 0, 9, 0, 9,
        7, 4, 2, 3, 5, 7, 7, 9, 2, 7, 0, 6, 0, 1, 8, 7, 2, 9, 4, 1, 7, 6, 1, 7,
        6, 5, 9, 3, 1, 4, 0, 6, 4, 1, 9, 0, 3, 7, 2, 9, 3, 0, 6, 2, 8, 2, 0, 2,
        6, 1, 0, 7, 2, 1, 4, 9, 6, 8, 8, 6, 4, 0, 9, 7, 1, 0, 6, 1, 3, 1, 8, 9,
        3, 7, 9, 4])
tensor([6, 4, 9, 1, 6, 1, 2, 8, 7, 7, 8, 0, 1, 8, 5, 2, 2, 0, 9, 5, 5, 5, 9, 1,
        2, 9, 4, 0, 2, 2, 5, 4, 6, 0, 5, 5, 8, 5, 7, 0, 4, 0, 9, 7, 7, 0, 3, 2,
        1, 1, 4, 9, 6, 0, 3, 8, 1, 1, 3, 2, 1, 1, 4, 3, 0, 2, 1, 1, 2, 7, 1, 0,
        8, 9, 3, 5, 7, 3, 9, 3, 4, 7, 9, 6, 1, 0, 6, 7, 6, 0, 9, 7, 7, 6, 4, 8

tensor([1, 1, 7, 6, 0, 2, 8, 1, 6, 1, 0, 4, 8, 3, 9, 9, 7, 2, 6, 6, 4, 3, 1, 9,
        6, 8, 9, 8, 8, 3, 3, 6, 9, 7, 1, 1, 5, 1, 3, 1, 4, 8, 7, 8, 7, 7, 7, 1,
        7, 3, 1, 3, 3, 9, 0, 4, 7, 9, 8, 0, 8, 9, 8, 7, 4, 9, 1, 3, 1, 3, 5, 0,
        9, 2, 0, 0, 8, 7, 7, 0, 7, 9, 6, 6, 8, 4, 7, 9, 2, 8, 8, 0, 2, 7, 2, 9,
        3, 2, 8, 3])
tensor([9, 8, 1, 4, 4, 2, 2, 1, 3, 7, 7, 2, 9, 9, 6, 5, 9, 5, 8, 2, 0, 9, 4, 3,
        6, 0, 8, 7, 2, 4, 9, 0, 3, 8, 4, 7, 6, 5, 4, 5, 7, 7, 3, 9, 4, 7, 8, 9,
        8, 7, 6, 6, 1, 0, 4, 4, 9, 9, 8, 4, 7, 7, 8, 8, 0, 8, 3, 2, 0, 0, 7, 6,
        2, 4, 0, 5, 2, 4, 0, 2, 7, 1, 7, 8, 1, 6, 1, 7, 7, 8, 6, 1, 9, 0, 4, 9,
        9, 6, 1, 1])
tensor([8, 4, 0, 9, 4, 8, 9, 5, 9, 2, 5, 4, 4, 7, 6, 9, 4, 1, 1, 3, 5, 0, 1, 8,
        8, 7, 1, 4, 6, 8, 8, 7, 9, 0, 9, 7, 2, 4, 4, 4, 9, 1, 6, 4, 6, 0, 9, 0,
        1, 0, 7, 1, 3, 7, 1, 8, 3, 8, 2, 3, 3, 3, 4, 5, 2, 5, 5, 7, 5, 4, 7, 4,
        0, 6, 0, 7, 3, 3, 8, 6, 9, 9, 4, 9, 3, 6, 3, 2, 1, 9, 2, 7, 8, 2, 7, 4

        3, 1, 0, 6])
tensor([5, 3, 3, 6, 8, 9, 1, 5, 8, 7, 4, 4, 8, 8, 8, 8, 5, 7, 9, 4, 7, 3, 3, 7,
        4, 9, 4, 4, 6, 7, 2, 9, 1, 6, 3, 4, 0, 9, 8, 8, 2, 8, 5, 6, 2, 3, 0, 4,
        1, 3, 8, 2, 1, 7, 8, 4, 1, 6, 6, 0, 1, 9, 2, 8, 8, 5, 0, 4, 1, 6, 1, 8,
        6, 9, 8, 7, 3, 1, 4, 5, 0, 7, 7, 7, 7, 4, 1, 3, 2, 8, 6, 7, 1, 2, 4, 6,
        2, 1, 6, 0])
tensor([8, 3, 2, 6, 7, 6, 6, 4, 1, 5, 0, 6, 4, 1, 1, 7, 8, 6, 1, 3, 5, 6, 5, 8,
        8, 3, 5, 8, 4, 6, 2, 1, 0, 4, 8, 4, 3, 8, 0, 7, 4, 4, 8, 3, 8, 4, 3, 5,
        5, 6, 8, 2, 5, 5, 9, 0, 2, 9, 3, 3, 1, 4, 0, 2, 7, 2, 4, 1, 8, 1, 4, 0,
        0, 2, 1, 9, 3, 9, 5, 6, 3, 8, 1, 7, 3, 1, 0, 4, 9, 5, 1, 3, 1, 2, 2, 1,
        9, 5, 5, 7])
tensor([7, 9, 6, 8, 0, 6, 0, 8, 7, 9, 5, 2, 2, 7, 4, 4, 4, 2, 8, 0, 1, 8, 0, 9,
        0, 3, 7, 4, 7, 8, 2, 5, 1, 8, 8, 8, 5, 6, 1, 3, 3, 6, 5, 9, 4, 0, 6, 1,
        4, 4, 9, 7, 2, 1, 0, 5, 0, 2, 5, 7, 7, 1, 0, 1, 4, 6, 9, 3, 7, 9, 1, 6,
        3, 1, 0, 8, 5, 4, 2, 9, 5, 9, 3, 2, 7, 2, 5, 6, 6

        7, 8, 6, 2])
tensor([6, 3, 6, 7, 6, 7, 8, 7, 9, 0, 1, 4, 7, 9, 4, 4, 9, 8, 1, 8, 0, 3, 1, 9,
        8, 9, 6, 2, 7, 6, 9, 2, 6, 1, 6, 2, 7, 6, 1, 7, 9, 3, 4, 5, 0, 4, 7, 6,
        5, 9, 2, 2, 7, 3, 2, 4, 8, 0, 3, 1, 5, 0, 1, 5, 7, 5, 0, 1, 7, 2, 6, 5,
        4, 2, 5, 9, 8, 4, 6, 7, 3, 2, 8, 8, 1, 5, 7, 5, 4, 2, 9, 1, 5, 9, 1, 1,
        8, 9, 0, 2])
tensor([0, 9, 8, 2, 9, 9, 7, 8, 2, 3, 1, 9, 0, 4, 6, 1, 0, 2, 2, 2, 2, 6, 3, 2,
        5, 9, 8, 9, 1, 3, 0, 0, 8, 7, 7, 4, 0, 6, 2, 6, 8, 9, 1, 4, 4, 0, 9, 6,
        4, 7, 1, 8, 5, 1, 1, 2, 6, 7, 0, 8, 8, 1, 5, 3, 5, 0, 1, 1, 2, 8, 9, 1,
        0, 3, 2, 6, 4, 9, 3, 1, 7, 1, 0, 6, 5, 6, 9, 6, 7, 8, 7, 7, 7, 9, 7, 9,
        1, 7, 6, 5])
tensor([8, 0, 5, 1, 4, 1, 5, 0, 3, 9, 4, 2, 8, 0, 5, 4, 1, 0, 4, 1, 6, 8, 5, 6,
        9, 2, 8, 1, 9, 0, 5, 0, 4, 8, 4, 5, 8, 1, 4, 8, 0, 9, 5, 3, 4, 6, 4, 5,
        9, 1, 8, 5, 3, 8, 3, 4, 2, 0, 8, 1, 0, 0, 7, 7, 4, 3, 9, 4, 9, 4, 8, 0,
        9, 5, 1, 3, 6, 1, 1, 1, 4, 1, 6, 8, 7, 3, 8, 1, 3

tensor([0, 3, 7, 9, 5, 2, 3, 6, 9, 2, 0, 0, 0, 2, 2, 1, 3, 5, 0, 9, 3, 6, 8, 6,
        5, 0, 0, 3, 5, 6, 3, 1, 6, 2, 4, 4, 1, 9, 8, 9, 1, 0, 9, 8, 3, 2, 4, 8,
        5, 0, 0, 4, 0, 7, 8, 3, 0, 1, 7, 1, 7, 4, 6, 2, 9, 2, 4, 5, 8, 4, 1, 0,
        1, 2, 3, 0, 6, 7, 3, 5, 3, 1, 8, 2, 0, 8, 9, 7, 3, 7, 2, 5, 3, 6, 3, 8,
        2, 6, 0, 4])
tensor([1, 0, 7, 6, 9, 7, 3, 1, 1, 3, 9, 3, 8, 0, 1, 8, 6, 0, 9, 2, 0, 2, 8, 8,
        3, 5, 1, 0, 4, 5, 7, 7, 8, 1, 3, 9, 3, 7, 3, 5, 2, 7, 4, 0, 4, 8, 7, 2,
        7, 6, 4, 7, 3, 1, 9, 0, 5, 9, 9, 5, 3, 8, 1, 0, 8, 1, 8, 2, 4, 3, 3, 1,
        3, 1, 3, 1, 2, 9, 9, 3, 6, 4, 2, 3, 1, 5, 4, 9, 4, 1, 9, 9, 5, 2, 7, 4,
        8, 7, 3, 0])
tensor([0, 2, 1, 3, 7, 8, 1, 5, 9, 4, 5, 2, 6, 0, 5, 1, 0, 8, 1, 1, 7, 7, 8, 8,
        0, 0, 6, 0, 4, 2, 9, 3, 1, 6, 1, 7, 3, 7, 7, 7, 9, 4, 9, 1, 6, 0, 6, 6,
        8, 1, 5, 9, 3, 6, 0, 5, 4, 0, 0, 1, 5, 3, 2, 5, 6, 8, 4, 7, 2, 9, 0, 3,
        6, 2, 5, 0, 8, 5, 2, 9, 4, 7, 4, 1, 2, 2, 1, 6, 1, 0, 2, 0, 9, 3, 1, 9

tensor([6, 6, 5, 6, 2, 4, 6, 7, 4, 7, 5, 1, 7, 1, 8, 9, 1, 1, 0, 4, 2, 8, 3, 7,
        5, 7, 2, 5, 9, 8, 1, 2, 0, 8, 2, 1, 8, 1, 7, 5, 9, 2, 4, 6, 5, 1, 0, 6,
        3, 6, 8, 6, 3, 6, 5, 4, 0, 8, 9, 7, 6, 7, 5, 1, 7, 0, 5, 4, 7, 1, 6, 2,
        3, 9, 7, 1, 8, 4, 4, 5, 1, 3, 5, 8, 3, 8, 4, 7, 5, 3, 2, 8, 8, 1, 0, 2,
        2, 9, 8, 4])
tensor([3, 2, 8, 4, 9, 0, 3, 1, 2, 3, 2, 1, 5, 7, 2, 9, 0, 2, 9, 3, 7, 3, 9, 2,
        4, 4, 2, 2, 6, 6, 5, 7, 1, 0, 0, 0, 7, 3, 4, 1, 7, 2, 2, 1, 5, 6, 2, 8,
        7, 9, 0, 1, 1, 6, 8, 8, 8, 5, 7, 6, 8, 3, 6, 8, 4, 3, 4, 4, 6, 1, 6, 3,
        3, 4, 6, 4, 1, 2, 9, 8, 3, 1, 2, 0, 7, 9, 4, 5, 8, 5, 1, 3, 0, 0, 8, 4,
        3, 1, 1, 0])
tensor([2, 2, 4, 3, 3, 0, 5, 8, 2, 4, 9, 6, 0, 7, 5, 6, 4, 1, 8, 3, 3, 4, 3, 4,
        5, 0, 1, 5, 4, 4, 6, 6, 9, 5, 0, 7, 1, 3, 0, 7, 4, 8, 5, 9, 3, 6, 3, 3,
        0, 0, 2, 1, 8, 1, 4, 6, 4, 3, 2, 7, 9, 6, 9, 1, 4, 5, 0, 3, 1, 3, 3, 1,
        9, 3, 6, 9, 7, 6, 6, 7, 4, 0, 0, 7, 3, 8, 4, 4, 6, 1, 2, 7, 7, 3, 9, 5

tensor([5, 4, 7, 2, 6, 2, 1, 8, 3, 7, 6, 7, 3, 3, 8, 5, 2, 0, 4, 8, 0, 2, 7, 5,
        1, 7, 5, 4, 5, 4, 7, 1, 6, 1, 7, 0, 1, 4, 0, 9, 1, 1, 4, 5, 0, 9, 2, 5,
        4, 9, 3, 3, 1, 2, 0, 2, 8, 6, 2, 6, 8, 2, 0, 0, 8, 7, 2, 6, 8, 4, 3, 3,
        8, 8, 8, 0, 3, 9, 7, 7, 1, 4, 0, 2, 9, 7, 1, 6, 6, 0, 8, 0, 3, 8, 2, 8,
        3, 5, 2, 9])
tensor([3, 9, 9, 3, 5, 0, 3, 2, 9, 6, 7, 6, 4, 4, 5, 3, 0, 7, 0, 4, 4, 3, 8, 9,
        2, 9, 4, 9, 5, 9, 4, 0, 4, 7, 0, 0, 6, 5, 3, 2, 4, 8, 6, 7, 9, 6, 3, 2,
        2, 4, 4, 1, 1, 5, 3, 2, 3, 8, 0, 6, 3, 5, 5, 1, 3, 3, 3, 4, 8, 2, 3, 9,
        1, 0, 7, 0, 2, 6, 1, 5, 2, 4, 9, 3, 9, 9, 1, 2, 0, 0, 7, 1, 8, 6, 7, 2,
        6, 3, 3, 9])
tensor([8, 7, 6, 2, 2, 2, 8, 4, 6, 4, 6, 6, 4, 8, 6, 5, 4, 9, 0, 0, 5, 1, 9, 0,
        9, 2, 4, 2, 9, 5, 5, 5, 3, 0, 2, 6, 7, 2, 5, 0, 9, 1, 7, 8, 4, 6, 4, 0,
        7, 3, 9, 0, 8, 4, 2, 4, 3, 2, 1, 8, 8, 4, 4, 4, 0, 0, 8, 6, 7, 4, 9, 5,
        3, 6, 4, 8, 9, 4, 4, 4, 4, 7, 1, 9, 1, 3, 4, 8, 7, 5, 1, 1, 2, 8, 7, 1

tensor([1, 9, 9, 6, 4, 8, 8, 4, 0, 0, 3, 1, 1, 2, 2, 4, 5, 1, 5, 2, 4, 0, 0, 8,
        4, 8, 4, 7, 8, 7, 9, 9, 7, 7, 9, 1, 2, 2, 9, 1, 1, 0, 1, 2, 1, 2, 7, 6,
        0, 1, 7, 7, 9, 3, 5, 4, 7, 4, 1, 7, 4, 9, 7, 3, 5, 1, 1, 1, 4, 1, 3, 9,
        3, 4, 3, 0, 3, 4, 3, 0, 2, 4, 3, 9, 2, 9, 5, 1, 9, 2, 4, 0, 2, 1, 8, 1,
        6, 4, 0, 7])
tensor([3, 2, 5, 7, 3, 1, 6, 4, 1, 5, 2, 5, 0, 4, 5, 2, 5, 4, 4, 6, 1, 3, 8, 9,
        4, 9, 1, 8, 6, 8, 9, 5, 8, 2, 3, 0, 1, 5, 5, 0, 3, 3, 9, 7, 6, 9, 6, 8,
        0, 1, 7, 7, 7, 0, 2, 9, 4, 8, 8, 9, 9, 0, 8, 9, 0, 7, 0, 0, 9, 1, 2, 7,
        4, 3, 3, 0, 7, 8, 1, 5, 1, 9, 6, 4, 8, 5, 2, 9, 5, 0, 7, 9, 2, 8, 1, 0,
        7, 0, 6, 0])
tensor([3, 8, 5, 3, 1, 8, 7, 8, 6, 7, 3, 7, 3, 8, 4, 9, 1, 7, 0, 7, 3, 3, 4, 1,
        8, 9, 1, 9, 2, 4, 6, 8, 2, 8, 7, 6, 5, 1, 5, 4, 4, 1, 1, 5, 0, 1, 4, 2,
        5, 0, 6, 7, 3, 9, 0, 5, 0, 1, 3, 1, 2, 4, 5, 7, 5, 4, 1, 3, 8, 2, 3, 7,
        4, 9, 8, 8, 8, 6, 4, 6, 0, 4, 9, 4, 9, 7, 0, 9, 9, 9, 5, 8, 3, 8, 0, 2

tensor([0, 6, 2, 0, 1, 8, 7, 3, 3, 8, 6, 2, 6, 9, 7, 5, 4, 7, 9, 0, 6, 0, 1, 6,
        0, 7, 5, 9, 1, 7, 5, 1, 1, 4, 8, 9, 7, 3, 9, 9, 5, 2, 5, 8, 6, 8, 0, 7,
        7, 2, 0, 1, 4, 9, 2, 4, 8, 4, 4, 6, 3, 0, 1, 6, 8, 6, 5, 1, 1, 4, 1, 9,
        1, 1, 4, 5, 4, 3, 4, 2, 2, 2, 3, 2, 1, 1, 5, 5, 1, 6, 1, 9, 3, 0, 3, 9,
        2, 8, 7, 0])
tensor([3, 9, 3, 0, 7, 3, 9, 6, 4, 8, 4, 8, 5, 2, 5, 8, 5, 4, 0, 4, 2, 9, 8, 4,
        2, 1, 3, 8, 9, 3, 1, 2, 8, 2, 3, 9, 7, 4, 2, 6, 8, 5, 0, 6, 5, 7, 7, 3,
        0, 6, 1, 9, 3, 2, 0, 7, 4, 7, 4, 0, 9, 5, 5, 1, 6, 3, 9, 3, 4, 1, 9, 4,
        7, 5, 0, 4, 3, 1, 9, 8, 4, 1, 1, 1, 9, 8, 6, 4, 7, 7, 7, 9, 8, 8, 3, 7,
        9, 1, 6, 7])
tensor([6, 9, 0, 2, 6, 5, 2, 5, 5, 3, 6, 1, 8, 0, 2, 1, 0, 4, 2, 1, 7, 0, 4, 8,
        2, 8, 3, 3, 7, 1, 1, 8, 6, 5, 5, 3, 9, 9, 1, 8, 4, 4, 1, 8, 5, 5, 5, 2,
        3, 3, 6, 1, 7, 3, 8, 0, 5, 1, 9, 3, 4, 7, 9, 0, 3, 7, 1, 7, 7, 0, 8, 1,
        8, 4, 5, 1, 4, 0, 9, 8, 5, 7, 9, 1, 6, 2, 6, 2, 2, 1, 7, 1, 9, 1, 5, 6

        1, 4, 5, 4])
tensor([2, 8, 9, 2, 7, 8, 3, 4, 3, 8, 8, 9, 3, 0, 8, 6, 1, 2, 5, 3, 0, 9, 0, 8,
        5, 2, 8, 5, 2, 6, 6, 9, 6, 8, 3, 3, 3, 0, 9, 1, 2, 7, 1, 2, 8, 6, 4, 1,
        3, 7, 3, 1, 3, 4, 4, 9, 6, 8, 9, 4, 7, 5, 6, 5, 4, 6, 6, 4, 7, 6, 2, 2,
        7, 5, 4, 8, 6, 8, 4, 2, 9, 3, 6, 2, 5, 2, 1, 8, 6, 9, 7, 1, 3, 6, 0, 9,
        9, 9, 5, 8])
tensor([1, 6, 4, 4, 1, 2, 1, 6, 3, 5, 8, 9, 8, 3, 1, 0, 8, 6, 1, 3, 0, 6, 0, 1,
        6, 9, 5, 6, 7, 9, 6, 5, 5, 0, 2, 7, 2, 7, 0, 5, 8, 1, 4, 1, 0, 6, 9, 4,
        0, 6, 6, 4, 1, 7, 1, 6, 8, 7, 3, 8, 9, 5, 0, 1, 7, 8, 4, 8, 4, 4, 8, 7,
        1, 3, 4, 6, 4, 2, 4, 6, 5, 7, 8, 4, 2, 1, 7, 5, 0, 5, 5, 4, 6, 7, 4, 7,
        9, 2, 4, 5])
tensor([6, 0, 8, 7, 0, 8, 8, 9, 3, 4, 1, 6, 7, 3, 3, 6, 5, 6, 7, 6, 9, 1, 9, 5,
        8, 4, 5, 6, 5, 0, 6, 9, 5, 5, 0, 1, 5, 9, 3, 3, 0, 5, 1, 6, 8, 3, 8, 4,
        1, 5, 0, 3, 5, 5, 0, 0, 7, 9, 4, 7, 0, 1, 2, 0, 9, 0, 9, 4, 5, 3, 8, 6,
        3, 3, 4, 9, 4, 3, 2, 7, 4, 7, 2, 8, 7, 3, 8, 0, 0

        1, 9, 7, 8])
tensor([1, 3, 8, 9, 2, 2, 3, 8, 8, 1, 9, 0, 1, 1, 8, 0, 0, 5, 3, 1, 4, 9, 6, 4,
        3, 6, 6, 7, 7, 1, 2, 0, 7, 2, 3, 8, 6, 8, 7, 3, 2, 2, 1, 5, 9, 6, 9, 3,
        1, 6, 5, 7, 7, 3, 7, 5, 4, 0, 0, 7, 9, 7, 0, 3, 4, 6, 8, 9, 0, 4, 7, 9,
        5, 7, 5, 7, 8, 1, 5, 7, 3, 4, 7, 3, 4, 1, 6, 4, 9, 4, 2, 3, 5, 7, 6, 8,
        9, 8, 8, 7])
tensor([2, 6, 9, 6, 1, 8, 1, 6, 4, 1, 7, 6, 3, 4, 7, 1, 1, 9, 0, 7, 2, 1, 1, 4,
        0, 5, 2, 0, 7, 1, 3, 4, 9, 2, 4, 5, 6, 4, 9, 1, 1, 7, 1, 5, 4, 2, 0, 5,
        5, 2, 8, 3, 0, 5, 4, 0, 6, 5, 1, 4, 0, 8, 7, 1, 4, 3, 4, 4, 4, 9, 5, 7,
        6, 8, 5, 9, 2, 0, 3, 7, 7, 1, 6, 7, 2, 3, 4, 2, 9, 9, 7, 8, 3, 2, 0, 4,
        7, 1, 6, 4])
tensor([2, 0, 2, 8, 6, 0, 9, 6, 9, 6, 8, 2, 9, 1, 6, 4, 1, 8, 1, 5, 1, 5, 7, 0,
        9, 2, 3, 7, 5, 7, 1, 7, 0, 2, 1, 5, 2, 3, 9, 5, 6, 2, 9, 5, 6, 1, 1, 8,
        9, 4, 3, 5, 0, 9, 0, 2, 8, 7, 2, 4, 7, 9, 1, 7, 7, 6, 2, 7, 5, 9, 3, 9,
        2, 0, 7, 0, 1, 7, 6, 4, 3, 8, 1, 3, 4, 0, 1, 6, 8

tensor([5, 4, 7, 3, 5, 1, 0, 0, 4, 6, 4, 3, 5, 3, 3, 3, 3, 7, 3, 5, 2, 1, 3, 2,
        1, 4, 7, 3, 8, 0, 4, 4, 6, 7, 4, 4, 4, 5, 0, 7, 9, 0, 7, 5, 2, 2, 1, 8,
        8, 1, 2, 9, 2, 9, 7, 5, 7, 1, 5, 3, 1, 7, 5, 3, 8, 9, 1, 1, 3, 0, 4, 3,
        8, 9, 9, 6, 4, 0, 6, 2, 2, 0, 4, 2, 0, 4, 1, 6, 5, 4, 5, 3, 0, 6, 3, 4,
        3, 1, 2, 2])
tensor([0, 1, 6, 0, 2, 4, 2, 8, 7, 8, 1, 5, 3, 2, 5, 0, 4, 0, 4, 5, 3, 8, 7, 8,
        4, 9, 5, 6, 5, 4, 2, 2, 2, 2, 6, 9, 0, 6, 7, 0, 8, 8, 5, 8, 7, 5, 0, 7,
        4, 6, 0, 9, 7, 9, 4, 4, 7, 8, 8, 0, 8, 8, 6, 9, 3, 9, 9, 2, 8, 4, 6, 2,
        8, 7, 1, 3, 2, 9, 4, 1, 3, 8, 5, 8, 8, 9, 0, 6, 3, 0, 1, 0, 2, 5, 7, 5,
        3, 8, 2, 9])
tensor([0, 6, 3, 0, 7, 2, 9, 9, 8, 3, 2, 5, 1, 3, 1, 3, 6, 4, 0, 1, 4, 7, 5, 6,
        2, 8, 7, 6, 9, 5, 0, 2, 6, 5, 1, 1, 3, 3, 3, 8, 3, 5, 4, 2, 6, 0, 7, 1,
        0, 9, 1, 2, 8, 0, 4, 1, 5, 4, 7, 9, 4, 3, 6, 5, 4, 2, 6, 1, 7, 8, 1, 2,
        3, 1, 4, 6, 1, 2, 9, 6, 3, 7, 1, 1, 1, 4, 1, 1, 0, 2, 9, 4, 9, 2, 0, 6

tensor([5, 0, 9, 7, 7, 8, 1, 7, 0, 1, 4, 3, 9, 5, 8, 4, 9, 0, 0, 5, 0, 6, 3, 4,
        3, 2, 3, 3, 2, 5, 4, 3, 4, 7, 8, 3, 1, 8, 1, 1, 5, 0, 4, 9, 4, 3, 6, 6,
        6, 8, 8, 8, 2, 7, 1, 1, 7, 1, 9, 1, 0, 6, 5, 6, 1, 2, 4, 5, 4, 6, 3, 1,
        3, 1, 7, 0, 5, 9, 5, 3, 0, 2, 7, 3, 2, 1, 5, 4, 9, 1, 2, 7, 7, 9, 8, 4,
        5, 0, 7, 6])
tensor([1, 2, 4, 7, 0, 6, 7, 1, 0, 6, 9, 5, 9, 0, 2, 7, 0, 2, 5, 7, 6, 1, 6, 1,
        6, 3, 2, 2, 2, 9, 0, 4, 3, 9, 8, 7, 2, 2, 1, 2, 5, 8, 6, 6, 7, 6, 4, 8,
        9, 3, 4, 2, 4, 4, 5, 6, 9, 7, 2, 0, 2, 3, 2, 3, 3, 2, 4, 7, 1, 4, 7, 0,
        8, 6, 9, 4, 1, 0, 7, 0, 6, 8, 6, 7, 3, 5, 0, 9, 2, 5, 5, 8, 0, 7, 6, 0,
        0, 9, 2, 3])
tensor([2, 0, 9, 5, 7, 8, 3, 2, 7, 0, 1, 3, 0, 9, 6, 8, 7, 6, 9, 8, 2, 2, 8, 4,
        9, 8, 2, 3, 1, 0, 7, 9, 2, 9, 1, 2, 0, 6, 0, 3, 2, 3, 1, 5, 3, 9, 0, 0,
        9, 2, 2, 0, 8, 8, 9, 3, 8, 0, 8, 3, 8, 9, 6, 2, 4, 4, 3, 3, 7, 7, 6, 7,
        9, 4, 9, 1, 9, 0, 0, 9, 1, 7, 1, 9, 4, 8, 8, 9, 5, 3, 1, 0, 8, 3, 6, 2

In [77]:
#### Train Model

iter = 0
for epoch in range(num_epochs):
    for i,(images,labels) in enumerate(train_loader):
        
        #Load images as Variable
        images = Variable(images.view(-1,28*28).cuda())
        labels = Variable(labels.cuda())
        
        #Clear gradients w.r.t. parameters
        optimizer.zero_grad()
        
        #Forward pass to get output/logits
        outputs=model(images)
        
        #Calculate Loss: Softmax -->cross entropy loss
        loss = criterion(outputs,labels)
        
        #Getting gradients w.r.t. parameters
        loss.backward()
        
        #Updating the parameters
        optimizer.step()
        
        iter+=1
        
        if iter%500==0:
            #Calculate accuracy
            correct = 0
            total = 0
            
            #Iterate through entire dataset
            for images,labels in test_loader:
                
                #Load images to a Torch Variable
                images = Variable(images.view(-1,28*28).cuda())
                
                #Forward pass only to get logits/output
                outputs = model(images)
                
                #Get predictions from the maximum value
                _,predicted = torch.max(outputs.data,1)
                
                #Total number of labels 
                total+=labels.size(0)
                
                #Total correct predictions
                correct += (predicted.cpu()==labels.cpu()).sum()
            
            accuracy = 100 * correct/total
            
            #Print loss
            print('Iteration: {}, Loss: {}, Accuracy: {}'.format(iter,loss.data,accuracy))
            

Iteration: 500, Loss: 0.3788561522960663, Accuracy: 90
Iteration: 1000, Loss: 0.28100794553756714, Accuracy: 93
Iteration: 1500, Loss: 0.12967155873775482, Accuracy: 94
Iteration: 2000, Loss: 0.16747285425662994, Accuracy: 95
Iteration: 2500, Loss: 0.1776425987482071, Accuracy: 95
Iteration: 3000, Loss: 0.12019386142492294, Accuracy: 96


### Convolutional Neural Networks

In [78]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.autograd import Variable

In [79]:
train_dataset = dsets.MNIST(root='./MNIST',train=True,transform=transforms.ToTensor(),download=True)

test_dataset = dsets.MNIST(root='./MNIST',train=False,transform=transforms.ToTensor())

In [80]:
#### Make Dataset Iterable

batch_size=100

n_iters = 3000

num_epochs = (n_iters*batch_size)/len(train_dataset)
num_epochs = int(num_epochs)
num_epochs

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,batch_size=batch_size,shuffle=False)

In [83]:
#### Create Model

class CNNModel(nn.Module):
    
    def __init__(self):
        super(CNNModel,self).__init__()
        
        #Convolution 1
        self.cnn1 = nn.Conv2d(in_channels=1,out_channels=16,kernel_size=5,stride=1,padding=2)
        self.relu1 = nn.ReLU()
        
        #Max pooling 1
        self.maxpool1 = nn.MaxPool2d(kernel_size=2)
        
        #Convolution 2
        self.cnn2 = nn.Conv2d(in_channels=16,out_channels=32,kernel_size=5,stride=1,padding=2)
        self.relu2 = nn.ReLU()
        
        #Max pooling 2
        self.maxpool2 = nn.MaxPool2d(kernel_size=2)
        
        #Fully Connected layer
        self.fc1 = nn.Linear(32*7*7,10)
        
    def forward(self,x):
        
        out = self.cnn1(x)
        out = self.relu1(out)
        
        out = self.maxpool1(out)
        
        out = self.cnn2(out)
        out = self.relu2(out)
        
        out = self.maxpool2(out)
        
        #Resize before feeding to the linear layer 
        out = out.view(out.size(0),-1)
        
        out = self.fc1(out)
        return out

In [92]:
#### Instantiate the Model
model = CNNModel()
model.cuda()

CNNModel(
  (cnn1): Conv2d(1, 16, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (relu1): ReLU()
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (cnn2): Conv2d(16, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (relu2): ReLU()
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=1568, out_features=10, bias=True)
)

In [93]:
#### Instantiate Loss Class

criterion = nn.CrossEntropyLoss()

In [94]:
#### Instantiate Optimizer Class


learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [95]:
#### Parameters in-depth

print(model.parameters())
print(len(list(model.parameters())))

#Conv 1: 16 kernels
print(list(model.parameters())[0].size())

#Conv 1 bias: 16 kernels 
print(list(model.parameters())[1].size())

#Conv 2 : 32 kernels with depth = 16
print(list(model.parameters())[2].size())

#Conv 2 bias: 32 kernels with depth = 16
print(list(model.parameters())[3].size())

#FC 1 layer 
print(list(model.parameters())[4].size())

#FC 1 layer bias
print(list(model.parameters())[5].size())

<generator object Module.parameters at 0x00000144653BAAF0>
6
torch.Size([16, 1, 5, 5])
torch.Size([16])
torch.Size([32, 16, 5, 5])
torch.Size([32])
torch.Size([10, 1568])
torch.Size([10])


In [96]:
print(len(train_loader))
for (images,labels) in train_loader:
    print(labels)

600
tensor([0, 0, 3, 9, 9, 7, 1, 3, 1, 2, 9, 7, 0, 2, 7, 9, 1, 0, 3, 5, 3, 4, 9, 9,
        0, 9, 4, 6, 0, 4, 0, 5, 0, 5, 9, 7, 5, 3, 0, 4, 0, 0, 4, 4, 4, 0, 5, 1,
        2, 2, 6, 6, 2, 8, 1, 4, 6, 3, 7, 0, 4, 1, 2, 7, 1, 6, 2, 8, 5, 5, 5, 0,
        8, 5, 2, 4, 6, 0, 9, 0, 9, 1, 2, 6, 9, 5, 3, 8, 3, 7, 9, 1, 3, 9, 9, 0,
        3, 7, 3, 1])
tensor([9, 4, 8, 8, 5, 3, 6, 6, 5, 1, 5, 0, 8, 0, 7, 1, 0, 2, 1, 5, 1, 5, 8, 6,
        2, 1, 2, 2, 5, 5, 3, 5, 4, 8, 7, 6, 0, 5, 8, 2, 4, 2, 4, 3, 2, 8, 8, 2,
        7, 7, 3, 8, 0, 9, 4, 7, 3, 0, 7, 5, 8, 5, 7, 0, 0, 7, 9, 7, 5, 8, 3, 5,
        9, 1, 6, 0, 0, 7, 8, 1, 8, 7, 6, 2, 3, 5, 6, 9, 6, 2, 9, 6, 6, 1, 9, 9,
        9, 4, 2, 3])
tensor([5, 7, 1, 5, 3, 9, 8, 3, 7, 2, 5, 0, 8, 1, 3, 7, 3, 6, 6, 3, 3, 3, 4, 5,
        2, 9, 7, 6, 9, 7, 2, 4, 2, 2, 4, 9, 7, 9, 6, 7, 3, 9, 5, 1, 3, 8, 5, 7,
        3, 2, 5, 2, 1, 1, 6, 4, 1, 4, 5, 1, 7, 2, 2, 2, 3, 8, 3, 7, 5, 9, 8, 1,
        1, 2, 2, 3, 7, 3, 4, 4, 4, 9, 1, 8, 8, 3, 5, 4, 5, 5, 1, 2, 0, 2, 

tensor([4, 2, 9, 9, 6, 7, 8, 1, 2, 1, 1, 7, 8, 1, 6, 8, 8, 0, 2, 7, 9, 1, 4, 5,
        5, 4, 4, 2, 6, 5, 2, 4, 3, 7, 8, 8, 8, 6, 7, 3, 5, 1, 3, 1, 9, 6, 5, 7,
        5, 7, 1, 5, 1, 0, 3, 1, 6, 3, 6, 0, 4, 8, 9, 4, 5, 7, 0, 5, 8, 1, 2, 0,
        0, 0, 6, 0, 4, 9, 2, 8, 1, 4, 8, 1, 2, 9, 5, 5, 6, 1, 6, 1, 9, 0, 5, 4,
        5, 4, 1, 4])
tensor([3, 2, 2, 1, 2, 4, 8, 5, 9, 1, 3, 9, 2, 9, 1, 1, 9, 7, 2, 8, 0, 1, 7, 6,
        4, 9, 2, 3, 7, 3, 9, 3, 3, 5, 9, 1, 0, 1, 1, 4, 5, 9, 1, 6, 8, 8, 3, 3,
        0, 4, 5, 1, 4, 3, 9, 1, 3, 0, 3, 0, 8, 1, 7, 2, 5, 7, 2, 7, 8, 6, 5, 2,
        7, 8, 7, 5, 7, 8, 4, 2, 0, 1, 0, 0, 6, 3, 1, 1, 8, 6, 1, 0, 8, 1, 3, 0,
        6, 0, 1, 7])
tensor([0, 2, 3, 6, 8, 7, 6, 2, 2, 3, 0, 3, 7, 9, 1, 5, 2, 8, 1, 3, 0, 2, 6, 2,
        4, 1, 5, 0, 1, 5, 0, 1, 6, 3, 0, 4, 0, 0, 2, 4, 4, 3, 4, 2, 7, 3, 2, 2,
        5, 7, 3, 6, 9, 7, 7, 5, 4, 5, 1, 8, 5, 1, 6, 7, 0, 2, 7, 8, 0, 0, 3, 5,
        4, 7, 2, 6, 1, 1, 1, 0, 3, 2, 9, 2, 0, 2, 1, 7, 5, 7, 3, 2, 3, 9, 7, 3

        2, 7, 1, 5])
tensor([9, 0, 7, 4, 2, 3, 7, 3, 9, 3, 9, 7, 3, 8, 4, 0, 8, 2, 2, 1, 7, 0, 6, 4,
        9, 4, 7, 1, 5, 7, 5, 1, 2, 1, 2, 3, 1, 8, 2, 5, 2, 7, 9, 1, 7, 0, 2, 9,
        8, 9, 4, 9, 5, 7, 6, 5, 3, 1, 5, 5, 4, 1, 0, 5, 5, 1, 5, 3, 3, 3, 7, 3,
        4, 4, 3, 9, 2, 9, 2, 0, 3, 7, 1, 3, 0, 8, 6, 7, 4, 5, 4, 0, 9, 0, 5, 5,
        1, 1, 2, 8])
tensor([4, 9, 1, 8, 6, 6, 8, 4, 4, 8, 8, 3, 5, 8, 6, 8, 1, 6, 4, 6, 2, 5, 1, 9,
        0, 1, 4, 9, 8, 9, 8, 8, 8, 2, 7, 0, 5, 8, 1, 3, 6, 6, 4, 5, 9, 9, 2, 6,
        3, 5, 9, 0, 4, 7, 2, 5, 8, 3, 8, 4, 1, 6, 0, 6, 6, 8, 2, 2, 8, 3, 1, 9,
        3, 2, 3, 6, 9, 1, 1, 4, 9, 1, 6, 7, 0, 2, 3, 8, 2, 1, 5, 8, 6, 6, 1, 9,
        4, 9, 0, 5])
tensor([0, 0, 2, 2, 4, 8, 6, 1, 2, 3, 4, 4, 9, 7, 4, 5, 8, 1, 6, 1, 0, 6, 0, 3,
        2, 7, 8, 8, 0, 5, 1, 1, 0, 2, 7, 5, 1, 2, 9, 5, 1, 7, 2, 8, 3, 3, 3, 5,
        7, 4, 7, 6, 7, 4, 2, 9, 5, 2, 9, 5, 1, 4, 7, 6, 1, 5, 1, 4, 2, 4, 8, 6,
        0, 5, 7, 2, 2, 1, 2, 1, 7, 9, 6, 3, 3, 2, 9, 3, 2

tensor([7, 3, 4, 3, 1, 4, 9, 1, 8, 2, 5, 9, 9, 8, 3, 6, 3, 6, 9, 4, 0, 6, 1, 8,
        5, 2, 6, 1, 3, 0, 1, 7, 7, 9, 7, 1, 0, 9, 7, 2, 7, 8, 2, 0, 1, 5, 5, 2,
        3, 8, 2, 5, 7, 9, 5, 1, 8, 5, 1, 8, 6, 1, 0, 8, 7, 8, 3, 5, 7, 3, 7, 2,
        5, 8, 1, 6, 1, 3, 8, 6, 7, 6, 0, 2, 4, 0, 9, 1, 1, 0, 7, 2, 0, 0, 6, 4,
        6, 6, 4, 9])
tensor([3, 5, 0, 7, 3, 8, 2, 8, 7, 2, 1, 9, 8, 2, 9, 0, 1, 0, 8, 2, 6, 9, 9, 1,
        9, 4, 0, 8, 6, 5, 1, 9, 0, 7, 1, 2, 1, 4, 2, 5, 2, 7, 2, 8, 7, 9, 5, 8,
        8, 4, 8, 3, 1, 5, 4, 5, 0, 6, 9, 0, 3, 0, 6, 4, 4, 3, 7, 5, 5, 9, 2, 8,
        5, 5, 1, 8, 2, 1, 5, 2, 0, 1, 3, 5, 9, 1, 6, 3, 1, 6, 1, 4, 6, 5, 6, 7,
        4, 1, 3, 4])
tensor([1, 3, 7, 3, 9, 8, 6, 0, 6, 4, 1, 3, 5, 6, 7, 2, 5, 6, 7, 5, 8, 7, 7, 7,
        8, 4, 7, 8, 2, 5, 4, 2, 3, 8, 5, 2, 2, 3, 1, 5, 1, 9, 6, 2, 4, 0, 4, 4,
        9, 1, 1, 7, 9, 2, 3, 7, 6, 2, 8, 3, 7, 9, 6, 4, 8, 4, 9, 2, 5, 6, 1, 6,
        9, 8, 8, 0, 6, 6, 4, 9, 0, 5, 7, 5, 7, 6, 9, 6, 5, 8, 0, 8, 4, 6, 6, 1

        0, 7, 3, 6])
tensor([6, 2, 3, 4, 0, 9, 6, 1, 0, 3, 3, 8, 6, 9, 5, 1, 6, 1, 7, 0, 4, 5, 6, 0,
        6, 9, 9, 8, 6, 4, 3, 0, 2, 4, 5, 7, 9, 7, 9, 9, 5, 9, 1, 2, 5, 4, 8, 3,
        5, 9, 6, 6, 0, 7, 6, 0, 0, 4, 3, 9, 4, 1, 9, 1, 5, 6, 1, 7, 1, 5, 7, 0,
        3, 4, 8, 4, 1, 9, 8, 2, 7, 5, 6, 5, 7, 5, 4, 0, 8, 1, 1, 4, 3, 2, 4, 3,
        9, 2, 1, 7])
tensor([5, 2, 6, 1, 9, 0, 8, 3, 9, 0, 9, 2, 8, 6, 6, 2, 5, 4, 5, 2, 0, 9, 1, 0,
        3, 0, 5, 0, 4, 1, 9, 3, 4, 1, 5, 0, 5, 3, 8, 9, 4, 8, 8, 0, 1, 8, 4, 8,
        7, 9, 4, 0, 9, 0, 8, 0, 0, 6, 4, 6, 8, 6, 0, 8, 2, 7, 4, 0, 7, 1, 5, 2,
        2, 1, 2, 8, 0, 2, 0, 0, 2, 7, 4, 1, 8, 9, 6, 1, 3, 1, 6, 2, 3, 6, 2, 0,
        5, 1, 0, 8])
tensor([3, 6, 6, 8, 1, 3, 0, 6, 0, 4, 5, 5, 9, 7, 4, 2, 6, 6, 8, 2, 5, 6, 4, 7,
        0, 5, 1, 8, 8, 6, 6, 6, 4, 4, 2, 9, 0, 3, 5, 1, 5, 5, 2, 2, 6, 0, 5, 5,
        5, 8, 3, 4, 3, 5, 4, 1, 0, 1, 8, 4, 3, 9, 4, 8, 3, 4, 1, 9, 1, 7, 8, 4,
        0, 9, 4, 5, 8, 4, 1, 9, 1, 9, 2, 4, 7, 8, 0, 7, 8

tensor([1, 4, 3, 7, 7, 7, 2, 7, 3, 8, 8, 7, 1, 7, 1, 8, 9, 8, 9, 2, 5, 2, 9, 9,
        3, 0, 1, 9, 7, 5, 1, 7, 5, 9, 6, 1, 4, 1, 6, 7, 7, 2, 1, 1, 0, 0, 3, 9,
        7, 6, 6, 8, 1, 1, 6, 2, 7, 8, 9, 9, 7, 2, 9, 1, 0, 1, 3, 9, 9, 2, 4, 0,
        7, 2, 9, 3, 2, 7, 6, 1, 4, 5, 6, 6, 7, 8, 4, 8, 0, 9, 3, 2, 7, 4, 4, 5,
        1, 9, 1, 4])
tensor([5, 5, 8, 4, 0, 5, 4, 6, 7, 9, 1, 8, 1, 3, 5, 9, 2, 8, 8, 4, 5, 5, 3, 5,
        2, 8, 1, 5, 0, 9, 0, 8, 9, 0, 4, 5, 3, 6, 1, 0, 6, 1, 3, 1, 9, 9, 3, 7,
        5, 0, 3, 1, 3, 5, 2, 1, 4, 6, 5, 7, 6, 3, 0, 6, 6, 9, 1, 0, 4, 9, 5, 3,
        0, 8, 8, 1, 5, 8, 1, 9, 5, 2, 6, 0, 8, 7, 2, 5, 2, 6, 8, 1, 7, 5, 7, 1,
        0, 9, 5, 1])
tensor([8, 6, 1, 0, 8, 4, 4, 0, 6, 3, 1, 0, 8, 8, 9, 4, 3, 3, 8, 9, 3, 4, 6, 8,
        7, 1, 1, 9, 9, 1, 8, 6, 7, 5, 0, 0, 2, 5, 9, 1, 2, 3, 4, 7, 7, 5, 8, 3,
        4, 7, 7, 2, 8, 6, 1, 2, 9, 8, 9, 1, 2, 3, 7, 1, 0, 0, 7, 7, 6, 5, 5, 4,
        9, 7, 0, 4, 1, 2, 0, 9, 6, 0, 0, 5, 6, 4, 3, 7, 4, 4, 6, 5, 2, 5, 0, 3

tensor([1, 7, 6, 7, 6, 7, 8, 7, 5, 0, 8, 6, 1, 5, 2, 6, 8, 7, 1, 4, 2, 6, 6, 3,
        0, 5, 1, 1, 2, 1, 4, 7, 0, 5, 3, 5, 1, 8, 1, 8, 8, 7, 7, 1, 1, 3, 9, 3,
        2, 8, 8, 6, 9, 7, 0, 4, 3, 6, 9, 3, 4, 9, 6, 7, 6, 6, 7, 4, 4, 6, 6, 1,
        9, 4, 1, 6, 1, 8, 4, 6, 0, 8, 7, 3, 9, 2, 0, 1, 6, 2, 4, 1, 8, 3, 0, 0,
        7, 7, 9, 1])
tensor([0, 9, 1, 4, 1, 5, 8, 0, 8, 4, 5, 0, 0, 8, 8, 5, 8, 5, 2, 2, 4, 4, 7, 1,
        4, 7, 0, 1, 7, 8, 9, 9, 5, 5, 6, 1, 6, 6, 6, 0, 7, 5, 6, 9, 7, 5, 3, 4,
        2, 7, 2, 7, 0, 0, 5, 0, 5, 1, 7, 7, 7, 0, 4, 2, 3, 5, 1, 0, 5, 0, 1, 0,
        2, 6, 8, 9, 3, 6, 6, 2, 4, 6, 0, 1, 9, 9, 2, 8, 5, 5, 7, 0, 9, 6, 9, 4,
        2, 9, 1, 4])
tensor([1, 9, 3, 3, 6, 0, 8, 2, 0, 4, 1, 3, 9, 1, 2, 9, 3, 6, 1, 0, 1, 6, 7, 7,
        0, 7, 8, 1, 6, 6, 0, 0, 5, 2, 9, 4, 5, 4, 9, 3, 2, 6, 4, 6, 4, 5, 7, 5,
        3, 8, 9, 4, 2, 6, 5, 5, 2, 2, 6, 5, 1, 9, 0, 1, 7, 5, 7, 9, 4, 5, 1, 2,
        2, 9, 7, 9, 8, 6, 8, 6, 4, 0, 7, 5, 5, 0, 0, 8, 1, 3, 8, 1, 9, 0, 9, 8

tensor([3, 8, 9, 6, 0, 0, 3, 5, 0, 2, 5, 4, 4, 4, 0, 2, 6, 3, 4, 9, 5, 3, 5, 6,
        5, 7, 0, 8, 0, 0, 7, 2, 4, 2, 4, 6, 9, 6, 0, 1, 7, 2, 9, 5, 0, 8, 0, 1,
        9, 4, 7, 1, 8, 5, 1, 6, 2, 7, 3, 1, 3, 8, 9, 7, 3, 5, 5, 0, 8, 1, 4, 4,
        8, 8, 2, 2, 2, 5, 1, 7, 7, 8, 5, 6, 1, 4, 0, 5, 9, 8, 4, 0, 3, 7, 4, 1,
        7, 0, 1, 6])
tensor([9, 4, 1, 2, 7, 0, 5, 1, 4, 5, 7, 2, 4, 7, 4, 8, 2, 8, 5, 5, 8, 3, 9, 2,
        7, 1, 5, 7, 8, 1, 7, 3, 8, 9, 0, 4, 4, 5, 5, 6, 0, 3, 0, 5, 8, 7, 7, 3,
        9, 2, 4, 3, 7, 6, 5, 3, 4, 0, 1, 6, 9, 0, 2, 4, 3, 7, 8, 0, 5, 9, 0, 4,
        3, 8, 1, 7, 9, 8, 4, 7, 0, 6, 4, 8, 5, 5, 4, 0, 9, 1, 7, 0, 8, 1, 2, 3,
        9, 0, 3, 0])
tensor([7, 7, 0, 4, 0, 7, 7, 7, 7, 2, 1, 5, 1, 0, 0, 5, 0, 2, 9, 1, 8, 2, 7, 4,
        9, 2, 0, 5, 7, 3, 6, 5, 4, 0, 3, 1, 6, 5, 2, 9, 3, 4, 4, 8, 8, 8, 2, 2,
        6, 9, 5, 6, 9, 4, 2, 8, 4, 9, 1, 3, 5, 1, 0, 6, 7, 6, 1, 5, 0, 9, 9, 3,
        7, 5, 2, 3, 9, 0, 6, 2, 3, 6, 0, 1, 4, 1, 4, 1, 1, 3, 6, 1, 4, 8, 7, 8

tensor([0, 9, 7, 0, 8, 0, 7, 6, 3, 2, 8, 6, 1, 5, 3, 7, 7, 8, 3, 9, 4, 3, 8, 1,
        0, 8, 7, 1, 2, 7, 3, 9, 7, 3, 4, 2, 8, 9, 9, 8, 5, 0, 6, 0, 5, 5, 0, 0,
        8, 9, 6, 6, 5, 9, 1, 3, 7, 9, 8, 1, 6, 5, 6, 5, 1, 9, 3, 6, 2, 8, 4, 8,
        7, 0, 2, 0, 8, 4, 8, 0, 7, 6, 2, 8, 7, 5, 9, 6, 3, 6, 0, 6, 6, 7, 0, 9,
        3, 3, 1, 2])
tensor([3, 7, 9, 1, 6, 8, 1, 9, 9, 2, 5, 0, 1, 8, 7, 5, 8, 6, 7, 1, 2, 5, 0, 7,
        1, 0, 9, 6, 5, 9, 1, 9, 0, 9, 8, 7, 1, 7, 7, 4, 4, 1, 0, 7, 1, 3, 6, 0,
        9, 6, 2, 5, 2, 1, 1, 9, 1, 6, 2, 9, 1, 1, 2, 3, 7, 6, 5, 7, 7, 0, 2, 7,
        8, 2, 9, 0, 5, 7, 3, 4, 5, 0, 2, 4, 5, 8, 0, 0, 6, 7, 9, 6, 6, 1, 2, 3,
        3, 9, 3, 0])
tensor([1, 9, 2, 9, 1, 6, 4, 5, 1, 4, 6, 1, 4, 1, 5, 2, 2, 8, 1, 7, 4, 2, 0, 9,
        3, 2, 9, 2, 3, 4, 4, 8, 3, 7, 9, 7, 6, 1, 5, 0, 4, 0, 4, 4, 8, 9, 2, 7,
        9, 6, 0, 1, 9, 2, 0, 8, 5, 8, 3, 8, 3, 3, 6, 1, 8, 6, 0, 0, 2, 4, 4, 2,
        3, 4, 9, 0, 0, 8, 7, 5, 5, 7, 7, 8, 2, 8, 1, 8, 7, 5, 9, 1, 6, 7, 8, 3

tensor([2, 3, 0, 0, 6, 0, 9, 7, 0, 0, 0, 0, 6, 1, 7, 5, 2, 8, 7, 3, 7, 2, 1, 3,
        4, 4, 4, 9, 7, 4, 5, 3, 2, 7, 9, 1, 9, 1, 9, 0, 3, 6, 3, 1, 0, 2, 6, 8,
        4, 1, 9, 5, 6, 8, 7, 5, 6, 2, 0, 4, 2, 2, 2, 1, 5, 8, 5, 0, 7, 3, 4, 7,
        2, 3, 3, 8, 2, 1, 0, 6, 1, 6, 1, 0, 6, 9, 1, 2, 1, 0, 8, 3, 0, 6, 7, 9,
        6, 1, 5, 0])
tensor([4, 7, 3, 6, 7, 9, 1, 2, 3, 8, 6, 3, 7, 0, 3, 5, 2, 9, 6, 1, 1, 3, 2, 3,
        5, 1, 9, 6, 2, 1, 9, 6, 4, 1, 3, 5, 6, 5, 5, 4, 3, 8, 8, 4, 1, 7, 1, 3,
        1, 8, 9, 6, 9, 3, 2, 3, 1, 1, 6, 5, 6, 5, 9, 2, 7, 5, 7, 0, 5, 5, 2, 7,
        4, 6, 8, 5, 5, 3, 6, 5, 4, 9, 7, 3, 7, 5, 3, 3, 8, 0, 9, 9, 8, 6, 1, 4,
        0, 0, 1, 8])
tensor([4, 3, 3, 8, 0, 3, 1, 3, 6, 0, 7, 0, 8, 8, 6, 6, 3, 8, 0, 8, 2, 2, 9, 1,
        4, 2, 4, 4, 9, 4, 2, 0, 5, 3, 4, 1, 2, 2, 6, 2, 5, 7, 1, 9, 1, 0, 1, 6,
        2, 7, 8, 5, 6, 0, 7, 2, 1, 6, 7, 5, 8, 8, 7, 2, 3, 8, 1, 0, 1, 3, 0, 6,
        0, 1, 0, 2, 0, 4, 9, 8, 9, 8, 3, 7, 2, 1, 2, 1, 1, 6, 0, 9, 0, 2, 2, 1

tensor([8, 8, 2, 8, 2, 7, 2, 3, 0, 7, 3, 9, 0, 5, 2, 3, 5, 0, 0, 4, 0, 9, 8, 8,
        4, 5, 3, 4, 5, 0, 7, 0, 7, 0, 5, 5, 6, 6, 5, 8, 6, 6, 5, 0, 5, 5, 9, 5,
        7, 8, 5, 6, 0, 7, 4, 5, 0, 4, 5, 7, 9, 5, 7, 8, 8, 6, 5, 9, 7, 9, 1, 0,
        8, 9, 7, 9, 3, 7, 6, 7, 4, 5, 4, 4, 5, 2, 2, 0, 2, 2, 5, 9, 8, 7, 3, 1,
        3, 4, 7, 0])
tensor([1, 2, 0, 8, 2, 8, 7, 8, 8, 2, 6, 2, 2, 4, 6, 9, 0, 8, 5, 8, 8, 4, 9, 2,
        7, 3, 4, 4, 0, 9, 8, 5, 5, 8, 0, 8, 2, 0, 9, 6, 0, 2, 8, 8, 4, 4, 4, 0,
        8, 5, 0, 9, 8, 8, 3, 7, 6, 1, 6, 0, 5, 5, 1, 8, 2, 1, 4, 7, 3, 6, 9, 6,
        2, 6, 2, 5, 2, 2, 1, 4, 4, 3, 1, 9, 6, 9, 4, 7, 9, 3, 5, 4, 4, 8, 1, 0,
        6, 0, 2, 7])
tensor([4, 9, 6, 0, 1, 7, 1, 1, 7, 3, 4, 2, 8, 7, 2, 7, 0, 2, 9, 5, 0, 8, 1, 3,
        1, 3, 0, 8, 4, 2, 8, 4, 6, 3, 3, 2, 2, 4, 6, 5, 3, 5, 5, 7, 7, 2, 4, 5,
        7, 6, 2, 1, 1, 8, 7, 7, 8, 8, 7, 6, 5, 2, 2, 6, 8, 4, 1, 7, 4, 4, 4, 7,
        2, 2, 0, 5, 3, 6, 6, 1, 3, 5, 4, 2, 5, 5, 3, 2, 1, 1, 7, 7, 2, 1, 7, 3

tensor([4, 7, 7, 1, 6, 1, 9, 6, 9, 8, 2, 5, 8, 2, 4, 8, 6, 7, 6, 0, 6, 1, 7, 6,
        6, 3, 5, 8, 0, 0, 5, 2, 9, 4, 7, 1, 2, 3, 5, 9, 6, 4, 4, 3, 8, 6, 8, 3,
        5, 6, 3, 4, 9, 6, 1, 6, 8, 8, 4, 8, 7, 2, 2, 3, 4, 1, 7, 9, 7, 9, 2, 8,
        9, 4, 8, 7, 1, 1, 6, 1, 6, 2, 2, 4, 6, 9, 9, 4, 3, 0, 3, 3, 8, 7, 9, 2,
        5, 0, 3, 7])
tensor([8, 9, 4, 8, 2, 1, 7, 2, 6, 2, 2, 6, 6, 8, 7, 5, 3, 5, 7, 5, 8, 1, 0, 9,
        8, 2, 8, 8, 8, 8, 6, 3, 1, 1, 9, 6, 1, 7, 2, 8, 5, 1, 1, 1, 1, 7, 4, 0,
        6, 8, 1, 3, 5, 2, 5, 2, 8, 0, 2, 8, 8, 2, 2, 8, 4, 6, 3, 3, 7, 3, 1, 3,
        4, 6, 4, 7, 7, 6, 5, 3, 7, 8, 3, 8, 8, 2, 2, 6, 4, 1, 9, 7, 9, 4, 3, 4,
        0, 9, 6, 6])
tensor([1, 3, 1, 8, 1, 7, 6, 8, 7, 7, 8, 8, 4, 1, 7, 0, 3, 6, 2, 0, 1, 1, 3, 0,
        8, 5, 3, 0, 5, 4, 8, 3, 1, 0, 9, 5, 5, 6, 4, 8, 7, 0, 2, 0, 8, 0, 4, 7,
        1, 9, 4, 8, 2, 8, 0, 6, 6, 1, 1, 2, 0, 2, 8, 6, 9, 5, 8, 4, 8, 1, 4, 9,
        7, 3, 3, 2, 4, 1, 7, 6, 3, 7, 2, 5, 6, 3, 7, 5, 5, 8, 5, 4, 0, 1, 4, 3

        6, 5, 8, 2])
tensor([8, 7, 0, 4, 0, 4, 2, 5, 2, 4, 5, 6, 4, 6, 8, 4, 3, 8, 1, 4, 0, 5, 7, 7,
        9, 1, 1, 2, 5, 7, 3, 5, 2, 4, 8, 1, 8, 0, 9, 9, 2, 1, 9, 8, 4, 5, 4, 4,
        1, 9, 0, 5, 1, 6, 3, 1, 1, 0, 1, 5, 7, 8, 3, 8, 6, 5, 2, 4, 4, 5, 0, 9,
        5, 2, 3, 7, 1, 7, 9, 0, 1, 7, 8, 9, 1, 2, 5, 0, 0, 7, 9, 2, 3, 1, 9, 3,
        2, 6, 6, 6])
tensor([3, 1, 5, 4, 0, 5, 7, 9, 4, 8, 3, 9, 2, 8, 9, 0, 0, 8, 9, 8, 9, 6, 8, 4,
        2, 9, 9, 5, 0, 2, 0, 2, 0, 6, 7, 1, 9, 1, 0, 6, 5, 4, 4, 0, 4, 9, 4, 6,
        7, 2, 6, 0, 4, 9, 8, 7, 8, 7, 3, 8, 3, 8, 3, 7, 8, 9, 9, 6, 9, 1, 2, 8,
        1, 5, 3, 8, 2, 3, 1, 8, 4, 4, 7, 4, 0, 9, 1, 7, 6, 7, 8, 5, 1, 8, 2, 5,
        5, 3, 9, 4])
tensor([1, 0, 8, 9, 4, 6, 0, 2, 5, 3, 4, 1, 0, 0, 9, 4, 7, 5, 1, 2, 2, 6, 5, 6,
        6, 2, 3, 3, 6, 5, 2, 6, 8, 3, 0, 0, 3, 0, 3, 9, 0, 6, 1, 5, 9, 3, 5, 2,
        0, 0, 0, 1, 2, 2, 2, 3, 3, 7, 8, 5, 8, 5, 6, 4, 2, 7, 1, 3, 9, 2, 0, 8,
        3, 0, 2, 6, 9, 8, 9, 9, 6, 6, 5, 1, 3, 7, 9, 1, 8

        0, 1, 9, 9])
tensor([8, 0, 1, 9, 7, 4, 1, 1, 4, 6, 7, 4, 6, 7, 3, 7, 8, 0, 1, 3, 5, 2, 8, 6,
        4, 2, 1, 4, 7, 3, 0, 0, 5, 0, 1, 6, 9, 5, 3, 7, 6, 6, 4, 1, 8, 5, 4, 8,
        1, 5, 6, 0, 4, 4, 9, 6, 1, 9, 5, 3, 7, 2, 1, 5, 6, 3, 9, 2, 5, 9, 5, 0,
        4, 3, 3, 1, 5, 2, 1, 7, 9, 5, 7, 6, 4, 1, 3, 7, 0, 6, 4, 2, 3, 4, 8, 0,
        7, 2, 9, 8])
tensor([4, 8, 5, 7, 4, 0, 8, 8, 3, 4, 7, 0, 5, 8, 2, 6, 0, 7, 1, 2, 2, 2, 1, 5,
        8, 0, 4, 0, 5, 0, 7, 3, 8, 1, 3, 2, 3, 4, 6, 2, 3, 6, 8, 0, 9, 2, 9, 1,
        1, 8, 0, 7, 7, 0, 1, 4, 3, 9, 8, 9, 6, 7, 0, 9, 5, 2, 0, 1, 6, 8, 6, 5,
        2, 1, 1, 0, 8, 9, 4, 8, 9, 1, 2, 1, 1, 3, 2, 8, 0, 7, 0, 9, 9, 8, 6, 1,
        4, 0, 0, 6])
tensor([2, 1, 5, 0, 5, 3, 2, 6, 9, 0, 1, 1, 4, 0, 0, 6, 2, 4, 9, 5, 4, 6, 6, 3,
        0, 2, 4, 9, 3, 6, 0, 4, 3, 3, 4, 2, 8, 8, 7, 1, 4, 5, 0, 6, 2, 3, 6, 3,
        1, 7, 0, 4, 0, 9, 7, 7, 7, 1, 9, 1, 6, 6, 5, 6, 6, 0, 2, 3, 7, 8, 6, 1,
        9, 3, 8, 9, 6, 3, 5, 7, 4, 1, 6, 9, 7, 9, 0, 1, 6

tensor([9, 2, 6, 6, 1, 4, 0, 9, 6, 1, 9, 7, 4, 2, 5, 5, 8, 5, 2, 8, 4, 9, 2, 9,
        3, 5, 7, 1, 7, 0, 7, 6, 5, 8, 8, 6, 3, 2, 8, 7, 6, 0, 2, 8, 1, 6, 1, 0,
        9, 6, 1, 7, 0, 3, 1, 4, 7, 3, 3, 0, 6, 9, 6, 5, 6, 9, 5, 1, 4, 6, 2, 2,
        8, 6, 1, 0, 2, 0, 9, 1, 3, 1, 3, 6, 4, 0, 6, 2, 6, 6, 6, 9, 1, 1, 0, 9,
        8, 2, 6, 8])
tensor([6, 0, 2, 1, 3, 1, 0, 3, 5, 7, 8, 5, 4, 8, 9, 3, 0, 4, 0, 3, 3, 0, 7, 5,
        0, 9, 0, 9, 7, 9, 4, 0, 1, 5, 3, 1, 2, 9, 0, 9, 3, 7, 6, 3, 4, 1, 8, 9,
        9, 5, 5, 4, 7, 6, 1, 2, 1, 3, 4, 1, 6, 2, 8, 9, 7, 5, 8, 4, 6, 7, 8, 0,
        1, 9, 2, 3, 5, 0, 1, 9, 4, 9, 7, 7, 2, 6, 2, 1, 4, 6, 9, 4, 2, 9, 8, 3,
        2, 7, 7, 0])
tensor([9, 5, 0, 1, 3, 6, 0, 0, 5, 8, 8, 3, 7, 5, 2, 7, 7, 3, 4, 6, 5, 4, 1, 5,
        2, 9, 0, 8, 4, 2, 3, 2, 6, 1, 9, 1, 6, 2, 0, 6, 9, 7, 9, 6, 4, 4, 8, 9,
        1, 8, 7, 2, 7, 3, 9, 0, 4, 8, 3, 3, 0, 8, 7, 1, 2, 1, 5, 9, 8, 2, 3, 7,
        1, 7, 8, 6, 0, 8, 3, 0, 2, 8, 7, 7, 7, 5, 6, 3, 2, 4, 5, 7, 4, 1, 9, 7

tensor([2, 1, 3, 9, 6, 1, 0, 5, 6, 6, 2, 4, 3, 6, 2, 7, 3, 2, 5, 8, 8, 6, 5, 8,
        0, 2, 5, 7, 0, 3, 6, 7, 9, 2, 9, 0, 8, 1, 3, 2, 5, 9, 1, 7, 1, 3, 1, 6,
        7, 9, 0, 5, 2, 5, 3, 0, 5, 9, 3, 3, 3, 4, 3, 3, 6, 7, 6, 1, 9, 4, 6, 5,
        0, 7, 3, 2, 5, 1, 0, 1, 5, 9, 2, 7, 4, 6, 5, 5, 4, 0, 7, 3, 3, 6, 1, 0,
        9, 4, 6, 1])
tensor([6, 3, 3, 3, 1, 2, 4, 1, 0, 4, 8, 6, 4, 9, 1, 2, 5, 5, 0, 9, 2, 5, 0, 0,
        6, 0, 8, 9, 0, 4, 4, 6, 3, 0, 6, 9, 7, 6, 1, 2, 2, 2, 9, 9, 9, 4, 2, 1,
        6, 8, 1, 0, 1, 0, 4, 3, 7, 7, 8, 5, 3, 5, 2, 8, 4, 7, 0, 7, 9, 4, 3, 2,
        4, 7, 4, 4, 5, 1, 0, 0, 2, 3, 6, 0, 3, 4, 4, 1, 1, 8, 6, 8, 5, 1, 0, 7,
        5, 3, 4, 3])
tensor([2, 1, 7, 2, 6, 4, 0, 9, 4, 8, 1, 4, 4, 7, 8, 6, 2, 7, 2, 2, 7, 1, 7, 8,
        1, 7, 1, 7, 9, 9, 4, 3, 3, 4, 9, 9, 2, 3, 5, 3, 1, 5, 7, 5, 5, 7, 6, 4,
        9, 1, 9, 5, 0, 0, 1, 1, 1, 8, 6, 3, 3, 5, 7, 2, 2, 8, 0, 8, 6, 7, 0, 1,
        1, 5, 7, 2, 5, 4, 7, 1, 8, 9, 9, 0, 3, 6, 8, 6, 0, 4, 9, 6, 6, 3, 1, 4

        8, 1, 7, 1])
tensor([9, 6, 7, 4, 1, 0, 8, 2, 9, 4, 3, 8, 2, 4, 6, 2, 9, 0, 8, 0, 1, 4, 2, 4,
        0, 8, 1, 6, 2, 1, 1, 9, 0, 3, 9, 8, 7, 6, 4, 2, 8, 9, 1, 6, 0, 6, 6, 2,
        6, 6, 6, 9, 9, 3, 4, 3, 4, 3, 7, 4, 8, 8, 3, 2, 6, 9, 3, 4, 8, 4, 5, 0,
        6, 2, 8, 9, 1, 4, 0, 9, 9, 6, 8, 0, 4, 8, 4, 7, 7, 6, 9, 7, 3, 7, 5, 4,
        1, 6, 1, 0])
tensor([9, 3, 1, 8, 4, 0, 5, 5, 6, 2, 6, 5, 5, 0, 6, 2, 4, 1, 2, 0, 6, 2, 3, 2,
        2, 1, 0, 9, 0, 0, 3, 0, 4, 2, 8, 8, 3, 9, 3, 7, 9, 2, 4, 2, 4, 6, 8, 1,
        7, 7, 9, 5, 6, 2, 8, 8, 8, 5, 6, 5, 9, 2, 2, 2, 5, 9, 7, 1, 7, 0, 9, 0,
        6, 0, 4, 1, 4, 7, 5, 0, 8, 9, 4, 6, 7, 0, 4, 3, 5, 4, 8, 8, 8, 9, 5, 2,
        9, 4, 7, 6])
tensor([3, 7, 2, 2, 8, 3, 3, 1, 4, 2, 0, 8, 5, 0, 3, 1, 3, 2, 4, 1, 5, 1, 1, 3,
        6, 7, 6, 7, 7, 0, 5, 7, 5, 7, 9, 5, 5, 2, 0, 2, 3, 9, 7, 1, 7, 1, 1, 3,
        1, 0, 7, 2, 6, 6, 0, 3, 8, 3, 6, 7, 5, 6, 1, 6, 0, 3, 8, 9, 8, 4, 2, 1,
        2, 5, 7, 5, 4, 2, 4, 4, 7, 6, 6, 2, 8, 5, 3, 0, 3

In [97]:
#### Train Model

iter = 0
for epoch in range(num_epochs):
    for i,(images,labels) in enumerate(train_loader):
        
        #Load images as Variable
        images = Variable(images.cuda())
        labels = Variable(labels.cuda())
        
        #Clear gradients w.r.t. parameters
        optimizer.zero_grad()
        
        #Forward pass to get output/logits
        outputs=model(images)
        
        #Calculate Loss: Softmax -->cross entropy loss
        loss = criterion(outputs,labels)
        
        #Getting gradients w.r.t. parameters
        loss.backward()
        
        #Updating the parameters
        optimizer.step()
        
        iter+=1
        
        if iter%500==0:
            #Calculate accuracy
            correct = 0
            total = 0
            
            #Iterate through entire dataset
            for images,labels in test_loader:
                
                #Load images to a Torch Variable
                images = Variable(images.cuda())
                
                #Forward pass only to get logits/output
                outputs = model(images)
                
                #Get predictions from the maximum value
                _,predicted = torch.max(outputs.data,1)
                
                #Total number of labels 
                total+=labels.size(0)
                
                #Total correct predictions
                correct += (predicted.cpu()==labels.cpu()).sum()
            
            accuracy = 100 * correct/total
            
            #Print loss
            print('Iteration: {}, Loss: {}, Accuracy: {}'.format(iter,loss.data,accuracy))
            

Iteration: 500, Loss: 0.5131245851516724, Accuracy: 89
Iteration: 1000, Loss: 0.20818428695201874, Accuracy: 92
Iteration: 1500, Loss: 0.15619687736034393, Accuracy: 94
Iteration: 2000, Loss: 0.17398256063461304, Accuracy: 95
Iteration: 2500, Loss: 0.15125831961631775, Accuracy: 96
Iteration: 3000, Loss: 0.09744241833686829, Accuracy: 96


### Recurrent Neural Network

In [78]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
from torch.autograd import Variable

In [79]:
train_dataset = dsets.MNIST(root='./MNIST',train=True,transform=transforms.ToTensor(),download=True)

test_dataset = dsets.MNIST(root='./MNIST',train=False,transform=transforms.ToTensor())

In [80]:
#### Make Dataset Iterable

batch_size=100

n_iters = 3000

num_epochs = (n_iters*batch_size)/len(train_dataset)
num_epochs = int(num_epochs)
num_epochs

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,batch_size=batch_size,shuffle=False)

In [83]:
#### Create Model

class RNNModel(nn.Module):
    
    def __init__(self,input_dim,hidden_dim,layer_dim,output_dim):
        super(RNNModel,self).__init__()
        
        #Hidden dimesions
        self.hidden = hidden_dim
        
        #Layer dimensions
        self.layer = layer_dim
        
        #Building RNN
        self.rnn = nn.RNN(input_dim,hidden_dim,layer_dim,batch_first=True,nonlinearity='relu')
        
        #Readout layer
        self.fc = nn.Linear(hidden_dim,output_dim)
        
    def forward(self,x):
        pass
    #Not completed

In [92]:
#### Instantiate the Model
model = CNNModel()
model.cuda()

CNNModel(
  (cnn1): Conv2d(1, 16, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (relu1): ReLU()
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (cnn2): Conv2d(16, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (relu2): ReLU()
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=1568, out_features=10, bias=True)
)

In [93]:
#### Instantiate Loss Class

criterion = nn.CrossEntropyLoss()

In [94]:
#### Instantiate Optimizer Class


learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [95]:
#### Parameters in-depth

print(model.parameters())
print(len(list(model.parameters())))

#Conv 1: 16 kernels
print(list(model.parameters())[0].size())

#Conv 1 bias: 16 kernels 
print(list(model.parameters())[1].size())

#Conv 2 : 32 kernels with depth = 16
print(list(model.parameters())[2].size())

#Conv 2 bias: 32 kernels with depth = 16
print(list(model.parameters())[3].size())

#FC 1 layer 
print(list(model.parameters())[4].size())

#FC 1 layer bias
print(list(model.parameters())[5].size())

<generator object Module.parameters at 0x00000144653BAAF0>
6
torch.Size([16, 1, 5, 5])
torch.Size([16])
torch.Size([32, 16, 5, 5])
torch.Size([32])
torch.Size([10, 1568])
torch.Size([10])


In [96]:
print(len(train_loader))
for (images,labels) in train_loader:
    print(labels)

600
tensor([0, 0, 3, 9, 9, 7, 1, 3, 1, 2, 9, 7, 0, 2, 7, 9, 1, 0, 3, 5, 3, 4, 9, 9,
        0, 9, 4, 6, 0, 4, 0, 5, 0, 5, 9, 7, 5, 3, 0, 4, 0, 0, 4, 4, 4, 0, 5, 1,
        2, 2, 6, 6, 2, 8, 1, 4, 6, 3, 7, 0, 4, 1, 2, 7, 1, 6, 2, 8, 5, 5, 5, 0,
        8, 5, 2, 4, 6, 0, 9, 0, 9, 1, 2, 6, 9, 5, 3, 8, 3, 7, 9, 1, 3, 9, 9, 0,
        3, 7, 3, 1])
tensor([9, 4, 8, 8, 5, 3, 6, 6, 5, 1, 5, 0, 8, 0, 7, 1, 0, 2, 1, 5, 1, 5, 8, 6,
        2, 1, 2, 2, 5, 5, 3, 5, 4, 8, 7, 6, 0, 5, 8, 2, 4, 2, 4, 3, 2, 8, 8, 2,
        7, 7, 3, 8, 0, 9, 4, 7, 3, 0, 7, 5, 8, 5, 7, 0, 0, 7, 9, 7, 5, 8, 3, 5,
        9, 1, 6, 0, 0, 7, 8, 1, 8, 7, 6, 2, 3, 5, 6, 9, 6, 2, 9, 6, 6, 1, 9, 9,
        9, 4, 2, 3])
tensor([5, 7, 1, 5, 3, 9, 8, 3, 7, 2, 5, 0, 8, 1, 3, 7, 3, 6, 6, 3, 3, 3, 4, 5,
        2, 9, 7, 6, 9, 7, 2, 4, 2, 2, 4, 9, 7, 9, 6, 7, 3, 9, 5, 1, 3, 8, 5, 7,
        3, 2, 5, 2, 1, 1, 6, 4, 1, 4, 5, 1, 7, 2, 2, 2, 3, 8, 3, 7, 5, 9, 8, 1,
        1, 2, 2, 3, 7, 3, 4, 4, 4, 9, 1, 8, 8, 3, 5, 4, 5, 5, 1, 2, 0, 2, 

tensor([4, 2, 9, 9, 6, 7, 8, 1, 2, 1, 1, 7, 8, 1, 6, 8, 8, 0, 2, 7, 9, 1, 4, 5,
        5, 4, 4, 2, 6, 5, 2, 4, 3, 7, 8, 8, 8, 6, 7, 3, 5, 1, 3, 1, 9, 6, 5, 7,
        5, 7, 1, 5, 1, 0, 3, 1, 6, 3, 6, 0, 4, 8, 9, 4, 5, 7, 0, 5, 8, 1, 2, 0,
        0, 0, 6, 0, 4, 9, 2, 8, 1, 4, 8, 1, 2, 9, 5, 5, 6, 1, 6, 1, 9, 0, 5, 4,
        5, 4, 1, 4])
tensor([3, 2, 2, 1, 2, 4, 8, 5, 9, 1, 3, 9, 2, 9, 1, 1, 9, 7, 2, 8, 0, 1, 7, 6,
        4, 9, 2, 3, 7, 3, 9, 3, 3, 5, 9, 1, 0, 1, 1, 4, 5, 9, 1, 6, 8, 8, 3, 3,
        0, 4, 5, 1, 4, 3, 9, 1, 3, 0, 3, 0, 8, 1, 7, 2, 5, 7, 2, 7, 8, 6, 5, 2,
        7, 8, 7, 5, 7, 8, 4, 2, 0, 1, 0, 0, 6, 3, 1, 1, 8, 6, 1, 0, 8, 1, 3, 0,
        6, 0, 1, 7])
tensor([0, 2, 3, 6, 8, 7, 6, 2, 2, 3, 0, 3, 7, 9, 1, 5, 2, 8, 1, 3, 0, 2, 6, 2,
        4, 1, 5, 0, 1, 5, 0, 1, 6, 3, 0, 4, 0, 0, 2, 4, 4, 3, 4, 2, 7, 3, 2, 2,
        5, 7, 3, 6, 9, 7, 7, 5, 4, 5, 1, 8, 5, 1, 6, 7, 0, 2, 7, 8, 0, 0, 3, 5,
        4, 7, 2, 6, 1, 1, 1, 0, 3, 2, 9, 2, 0, 2, 1, 7, 5, 7, 3, 2, 3, 9, 7, 3

        2, 7, 1, 5])
tensor([9, 0, 7, 4, 2, 3, 7, 3, 9, 3, 9, 7, 3, 8, 4, 0, 8, 2, 2, 1, 7, 0, 6, 4,
        9, 4, 7, 1, 5, 7, 5, 1, 2, 1, 2, 3, 1, 8, 2, 5, 2, 7, 9, 1, 7, 0, 2, 9,
        8, 9, 4, 9, 5, 7, 6, 5, 3, 1, 5, 5, 4, 1, 0, 5, 5, 1, 5, 3, 3, 3, 7, 3,
        4, 4, 3, 9, 2, 9, 2, 0, 3, 7, 1, 3, 0, 8, 6, 7, 4, 5, 4, 0, 9, 0, 5, 5,
        1, 1, 2, 8])
tensor([4, 9, 1, 8, 6, 6, 8, 4, 4, 8, 8, 3, 5, 8, 6, 8, 1, 6, 4, 6, 2, 5, 1, 9,
        0, 1, 4, 9, 8, 9, 8, 8, 8, 2, 7, 0, 5, 8, 1, 3, 6, 6, 4, 5, 9, 9, 2, 6,
        3, 5, 9, 0, 4, 7, 2, 5, 8, 3, 8, 4, 1, 6, 0, 6, 6, 8, 2, 2, 8, 3, 1, 9,
        3, 2, 3, 6, 9, 1, 1, 4, 9, 1, 6, 7, 0, 2, 3, 8, 2, 1, 5, 8, 6, 6, 1, 9,
        4, 9, 0, 5])
tensor([0, 0, 2, 2, 4, 8, 6, 1, 2, 3, 4, 4, 9, 7, 4, 5, 8, 1, 6, 1, 0, 6, 0, 3,
        2, 7, 8, 8, 0, 5, 1, 1, 0, 2, 7, 5, 1, 2, 9, 5, 1, 7, 2, 8, 3, 3, 3, 5,
        7, 4, 7, 6, 7, 4, 2, 9, 5, 2, 9, 5, 1, 4, 7, 6, 1, 5, 1, 4, 2, 4, 8, 6,
        0, 5, 7, 2, 2, 1, 2, 1, 7, 9, 6, 3, 3, 2, 9, 3, 2

tensor([7, 3, 4, 3, 1, 4, 9, 1, 8, 2, 5, 9, 9, 8, 3, 6, 3, 6, 9, 4, 0, 6, 1, 8,
        5, 2, 6, 1, 3, 0, 1, 7, 7, 9, 7, 1, 0, 9, 7, 2, 7, 8, 2, 0, 1, 5, 5, 2,
        3, 8, 2, 5, 7, 9, 5, 1, 8, 5, 1, 8, 6, 1, 0, 8, 7, 8, 3, 5, 7, 3, 7, 2,
        5, 8, 1, 6, 1, 3, 8, 6, 7, 6, 0, 2, 4, 0, 9, 1, 1, 0, 7, 2, 0, 0, 6, 4,
        6, 6, 4, 9])
tensor([3, 5, 0, 7, 3, 8, 2, 8, 7, 2, 1, 9, 8, 2, 9, 0, 1, 0, 8, 2, 6, 9, 9, 1,
        9, 4, 0, 8, 6, 5, 1, 9, 0, 7, 1, 2, 1, 4, 2, 5, 2, 7, 2, 8, 7, 9, 5, 8,
        8, 4, 8, 3, 1, 5, 4, 5, 0, 6, 9, 0, 3, 0, 6, 4, 4, 3, 7, 5, 5, 9, 2, 8,
        5, 5, 1, 8, 2, 1, 5, 2, 0, 1, 3, 5, 9, 1, 6, 3, 1, 6, 1, 4, 6, 5, 6, 7,
        4, 1, 3, 4])
tensor([1, 3, 7, 3, 9, 8, 6, 0, 6, 4, 1, 3, 5, 6, 7, 2, 5, 6, 7, 5, 8, 7, 7, 7,
        8, 4, 7, 8, 2, 5, 4, 2, 3, 8, 5, 2, 2, 3, 1, 5, 1, 9, 6, 2, 4, 0, 4, 4,
        9, 1, 1, 7, 9, 2, 3, 7, 6, 2, 8, 3, 7, 9, 6, 4, 8, 4, 9, 2, 5, 6, 1, 6,
        9, 8, 8, 0, 6, 6, 4, 9, 0, 5, 7, 5, 7, 6, 9, 6, 5, 8, 0, 8, 4, 6, 6, 1

        0, 7, 3, 6])
tensor([6, 2, 3, 4, 0, 9, 6, 1, 0, 3, 3, 8, 6, 9, 5, 1, 6, 1, 7, 0, 4, 5, 6, 0,
        6, 9, 9, 8, 6, 4, 3, 0, 2, 4, 5, 7, 9, 7, 9, 9, 5, 9, 1, 2, 5, 4, 8, 3,
        5, 9, 6, 6, 0, 7, 6, 0, 0, 4, 3, 9, 4, 1, 9, 1, 5, 6, 1, 7, 1, 5, 7, 0,
        3, 4, 8, 4, 1, 9, 8, 2, 7, 5, 6, 5, 7, 5, 4, 0, 8, 1, 1, 4, 3, 2, 4, 3,
        9, 2, 1, 7])
tensor([5, 2, 6, 1, 9, 0, 8, 3, 9, 0, 9, 2, 8, 6, 6, 2, 5, 4, 5, 2, 0, 9, 1, 0,
        3, 0, 5, 0, 4, 1, 9, 3, 4, 1, 5, 0, 5, 3, 8, 9, 4, 8, 8, 0, 1, 8, 4, 8,
        7, 9, 4, 0, 9, 0, 8, 0, 0, 6, 4, 6, 8, 6, 0, 8, 2, 7, 4, 0, 7, 1, 5, 2,
        2, 1, 2, 8, 0, 2, 0, 0, 2, 7, 4, 1, 8, 9, 6, 1, 3, 1, 6, 2, 3, 6, 2, 0,
        5, 1, 0, 8])
tensor([3, 6, 6, 8, 1, 3, 0, 6, 0, 4, 5, 5, 9, 7, 4, 2, 6, 6, 8, 2, 5, 6, 4, 7,
        0, 5, 1, 8, 8, 6, 6, 6, 4, 4, 2, 9, 0, 3, 5, 1, 5, 5, 2, 2, 6, 0, 5, 5,
        5, 8, 3, 4, 3, 5, 4, 1, 0, 1, 8, 4, 3, 9, 4, 8, 3, 4, 1, 9, 1, 7, 8, 4,
        0, 9, 4, 5, 8, 4, 1, 9, 1, 9, 2, 4, 7, 8, 0, 7, 8

tensor([1, 4, 3, 7, 7, 7, 2, 7, 3, 8, 8, 7, 1, 7, 1, 8, 9, 8, 9, 2, 5, 2, 9, 9,
        3, 0, 1, 9, 7, 5, 1, 7, 5, 9, 6, 1, 4, 1, 6, 7, 7, 2, 1, 1, 0, 0, 3, 9,
        7, 6, 6, 8, 1, 1, 6, 2, 7, 8, 9, 9, 7, 2, 9, 1, 0, 1, 3, 9, 9, 2, 4, 0,
        7, 2, 9, 3, 2, 7, 6, 1, 4, 5, 6, 6, 7, 8, 4, 8, 0, 9, 3, 2, 7, 4, 4, 5,
        1, 9, 1, 4])
tensor([5, 5, 8, 4, 0, 5, 4, 6, 7, 9, 1, 8, 1, 3, 5, 9, 2, 8, 8, 4, 5, 5, 3, 5,
        2, 8, 1, 5, 0, 9, 0, 8, 9, 0, 4, 5, 3, 6, 1, 0, 6, 1, 3, 1, 9, 9, 3, 7,
        5, 0, 3, 1, 3, 5, 2, 1, 4, 6, 5, 7, 6, 3, 0, 6, 6, 9, 1, 0, 4, 9, 5, 3,
        0, 8, 8, 1, 5, 8, 1, 9, 5, 2, 6, 0, 8, 7, 2, 5, 2, 6, 8, 1, 7, 5, 7, 1,
        0, 9, 5, 1])
tensor([8, 6, 1, 0, 8, 4, 4, 0, 6, 3, 1, 0, 8, 8, 9, 4, 3, 3, 8, 9, 3, 4, 6, 8,
        7, 1, 1, 9, 9, 1, 8, 6, 7, 5, 0, 0, 2, 5, 9, 1, 2, 3, 4, 7, 7, 5, 8, 3,
        4, 7, 7, 2, 8, 6, 1, 2, 9, 8, 9, 1, 2, 3, 7, 1, 0, 0, 7, 7, 6, 5, 5, 4,
        9, 7, 0, 4, 1, 2, 0, 9, 6, 0, 0, 5, 6, 4, 3, 7, 4, 4, 6, 5, 2, 5, 0, 3

tensor([1, 7, 6, 7, 6, 7, 8, 7, 5, 0, 8, 6, 1, 5, 2, 6, 8, 7, 1, 4, 2, 6, 6, 3,
        0, 5, 1, 1, 2, 1, 4, 7, 0, 5, 3, 5, 1, 8, 1, 8, 8, 7, 7, 1, 1, 3, 9, 3,
        2, 8, 8, 6, 9, 7, 0, 4, 3, 6, 9, 3, 4, 9, 6, 7, 6, 6, 7, 4, 4, 6, 6, 1,
        9, 4, 1, 6, 1, 8, 4, 6, 0, 8, 7, 3, 9, 2, 0, 1, 6, 2, 4, 1, 8, 3, 0, 0,
        7, 7, 9, 1])
tensor([0, 9, 1, 4, 1, 5, 8, 0, 8, 4, 5, 0, 0, 8, 8, 5, 8, 5, 2, 2, 4, 4, 7, 1,
        4, 7, 0, 1, 7, 8, 9, 9, 5, 5, 6, 1, 6, 6, 6, 0, 7, 5, 6, 9, 7, 5, 3, 4,
        2, 7, 2, 7, 0, 0, 5, 0, 5, 1, 7, 7, 7, 0, 4, 2, 3, 5, 1, 0, 5, 0, 1, 0,
        2, 6, 8, 9, 3, 6, 6, 2, 4, 6, 0, 1, 9, 9, 2, 8, 5, 5, 7, 0, 9, 6, 9, 4,
        2, 9, 1, 4])
tensor([1, 9, 3, 3, 6, 0, 8, 2, 0, 4, 1, 3, 9, 1, 2, 9, 3, 6, 1, 0, 1, 6, 7, 7,
        0, 7, 8, 1, 6, 6, 0, 0, 5, 2, 9, 4, 5, 4, 9, 3, 2, 6, 4, 6, 4, 5, 7, 5,
        3, 8, 9, 4, 2, 6, 5, 5, 2, 2, 6, 5, 1, 9, 0, 1, 7, 5, 7, 9, 4, 5, 1, 2,
        2, 9, 7, 9, 8, 6, 8, 6, 4, 0, 7, 5, 5, 0, 0, 8, 1, 3, 8, 1, 9, 0, 9, 8

tensor([3, 8, 9, 6, 0, 0, 3, 5, 0, 2, 5, 4, 4, 4, 0, 2, 6, 3, 4, 9, 5, 3, 5, 6,
        5, 7, 0, 8, 0, 0, 7, 2, 4, 2, 4, 6, 9, 6, 0, 1, 7, 2, 9, 5, 0, 8, 0, 1,
        9, 4, 7, 1, 8, 5, 1, 6, 2, 7, 3, 1, 3, 8, 9, 7, 3, 5, 5, 0, 8, 1, 4, 4,
        8, 8, 2, 2, 2, 5, 1, 7, 7, 8, 5, 6, 1, 4, 0, 5, 9, 8, 4, 0, 3, 7, 4, 1,
        7, 0, 1, 6])
tensor([9, 4, 1, 2, 7, 0, 5, 1, 4, 5, 7, 2, 4, 7, 4, 8, 2, 8, 5, 5, 8, 3, 9, 2,
        7, 1, 5, 7, 8, 1, 7, 3, 8, 9, 0, 4, 4, 5, 5, 6, 0, 3, 0, 5, 8, 7, 7, 3,
        9, 2, 4, 3, 7, 6, 5, 3, 4, 0, 1, 6, 9, 0, 2, 4, 3, 7, 8, 0, 5, 9, 0, 4,
        3, 8, 1, 7, 9, 8, 4, 7, 0, 6, 4, 8, 5, 5, 4, 0, 9, 1, 7, 0, 8, 1, 2, 3,
        9, 0, 3, 0])
tensor([7, 7, 0, 4, 0, 7, 7, 7, 7, 2, 1, 5, 1, 0, 0, 5, 0, 2, 9, 1, 8, 2, 7, 4,
        9, 2, 0, 5, 7, 3, 6, 5, 4, 0, 3, 1, 6, 5, 2, 9, 3, 4, 4, 8, 8, 8, 2, 2,
        6, 9, 5, 6, 9, 4, 2, 8, 4, 9, 1, 3, 5, 1, 0, 6, 7, 6, 1, 5, 0, 9, 9, 3,
        7, 5, 2, 3, 9, 0, 6, 2, 3, 6, 0, 1, 4, 1, 4, 1, 1, 3, 6, 1, 4, 8, 7, 8

tensor([0, 9, 7, 0, 8, 0, 7, 6, 3, 2, 8, 6, 1, 5, 3, 7, 7, 8, 3, 9, 4, 3, 8, 1,
        0, 8, 7, 1, 2, 7, 3, 9, 7, 3, 4, 2, 8, 9, 9, 8, 5, 0, 6, 0, 5, 5, 0, 0,
        8, 9, 6, 6, 5, 9, 1, 3, 7, 9, 8, 1, 6, 5, 6, 5, 1, 9, 3, 6, 2, 8, 4, 8,
        7, 0, 2, 0, 8, 4, 8, 0, 7, 6, 2, 8, 7, 5, 9, 6, 3, 6, 0, 6, 6, 7, 0, 9,
        3, 3, 1, 2])
tensor([3, 7, 9, 1, 6, 8, 1, 9, 9, 2, 5, 0, 1, 8, 7, 5, 8, 6, 7, 1, 2, 5, 0, 7,
        1, 0, 9, 6, 5, 9, 1, 9, 0, 9, 8, 7, 1, 7, 7, 4, 4, 1, 0, 7, 1, 3, 6, 0,
        9, 6, 2, 5, 2, 1, 1, 9, 1, 6, 2, 9, 1, 1, 2, 3, 7, 6, 5, 7, 7, 0, 2, 7,
        8, 2, 9, 0, 5, 7, 3, 4, 5, 0, 2, 4, 5, 8, 0, 0, 6, 7, 9, 6, 6, 1, 2, 3,
        3, 9, 3, 0])
tensor([1, 9, 2, 9, 1, 6, 4, 5, 1, 4, 6, 1, 4, 1, 5, 2, 2, 8, 1, 7, 4, 2, 0, 9,
        3, 2, 9, 2, 3, 4, 4, 8, 3, 7, 9, 7, 6, 1, 5, 0, 4, 0, 4, 4, 8, 9, 2, 7,
        9, 6, 0, 1, 9, 2, 0, 8, 5, 8, 3, 8, 3, 3, 6, 1, 8, 6, 0, 0, 2, 4, 4, 2,
        3, 4, 9, 0, 0, 8, 7, 5, 5, 7, 7, 8, 2, 8, 1, 8, 7, 5, 9, 1, 6, 7, 8, 3

tensor([2, 3, 0, 0, 6, 0, 9, 7, 0, 0, 0, 0, 6, 1, 7, 5, 2, 8, 7, 3, 7, 2, 1, 3,
        4, 4, 4, 9, 7, 4, 5, 3, 2, 7, 9, 1, 9, 1, 9, 0, 3, 6, 3, 1, 0, 2, 6, 8,
        4, 1, 9, 5, 6, 8, 7, 5, 6, 2, 0, 4, 2, 2, 2, 1, 5, 8, 5, 0, 7, 3, 4, 7,
        2, 3, 3, 8, 2, 1, 0, 6, 1, 6, 1, 0, 6, 9, 1, 2, 1, 0, 8, 3, 0, 6, 7, 9,
        6, 1, 5, 0])
tensor([4, 7, 3, 6, 7, 9, 1, 2, 3, 8, 6, 3, 7, 0, 3, 5, 2, 9, 6, 1, 1, 3, 2, 3,
        5, 1, 9, 6, 2, 1, 9, 6, 4, 1, 3, 5, 6, 5, 5, 4, 3, 8, 8, 4, 1, 7, 1, 3,
        1, 8, 9, 6, 9, 3, 2, 3, 1, 1, 6, 5, 6, 5, 9, 2, 7, 5, 7, 0, 5, 5, 2, 7,
        4, 6, 8, 5, 5, 3, 6, 5, 4, 9, 7, 3, 7, 5, 3, 3, 8, 0, 9, 9, 8, 6, 1, 4,
        0, 0, 1, 8])
tensor([4, 3, 3, 8, 0, 3, 1, 3, 6, 0, 7, 0, 8, 8, 6, 6, 3, 8, 0, 8, 2, 2, 9, 1,
        4, 2, 4, 4, 9, 4, 2, 0, 5, 3, 4, 1, 2, 2, 6, 2, 5, 7, 1, 9, 1, 0, 1, 6,
        2, 7, 8, 5, 6, 0, 7, 2, 1, 6, 7, 5, 8, 8, 7, 2, 3, 8, 1, 0, 1, 3, 0, 6,
        0, 1, 0, 2, 0, 4, 9, 8, 9, 8, 3, 7, 2, 1, 2, 1, 1, 6, 0, 9, 0, 2, 2, 1

tensor([8, 8, 2, 8, 2, 7, 2, 3, 0, 7, 3, 9, 0, 5, 2, 3, 5, 0, 0, 4, 0, 9, 8, 8,
        4, 5, 3, 4, 5, 0, 7, 0, 7, 0, 5, 5, 6, 6, 5, 8, 6, 6, 5, 0, 5, 5, 9, 5,
        7, 8, 5, 6, 0, 7, 4, 5, 0, 4, 5, 7, 9, 5, 7, 8, 8, 6, 5, 9, 7, 9, 1, 0,
        8, 9, 7, 9, 3, 7, 6, 7, 4, 5, 4, 4, 5, 2, 2, 0, 2, 2, 5, 9, 8, 7, 3, 1,
        3, 4, 7, 0])
tensor([1, 2, 0, 8, 2, 8, 7, 8, 8, 2, 6, 2, 2, 4, 6, 9, 0, 8, 5, 8, 8, 4, 9, 2,
        7, 3, 4, 4, 0, 9, 8, 5, 5, 8, 0, 8, 2, 0, 9, 6, 0, 2, 8, 8, 4, 4, 4, 0,
        8, 5, 0, 9, 8, 8, 3, 7, 6, 1, 6, 0, 5, 5, 1, 8, 2, 1, 4, 7, 3, 6, 9, 6,
        2, 6, 2, 5, 2, 2, 1, 4, 4, 3, 1, 9, 6, 9, 4, 7, 9, 3, 5, 4, 4, 8, 1, 0,
        6, 0, 2, 7])
tensor([4, 9, 6, 0, 1, 7, 1, 1, 7, 3, 4, 2, 8, 7, 2, 7, 0, 2, 9, 5, 0, 8, 1, 3,
        1, 3, 0, 8, 4, 2, 8, 4, 6, 3, 3, 2, 2, 4, 6, 5, 3, 5, 5, 7, 7, 2, 4, 5,
        7, 6, 2, 1, 1, 8, 7, 7, 8, 8, 7, 6, 5, 2, 2, 6, 8, 4, 1, 7, 4, 4, 4, 7,
        2, 2, 0, 5, 3, 6, 6, 1, 3, 5, 4, 2, 5, 5, 3, 2, 1, 1, 7, 7, 2, 1, 7, 3

tensor([4, 7, 7, 1, 6, 1, 9, 6, 9, 8, 2, 5, 8, 2, 4, 8, 6, 7, 6, 0, 6, 1, 7, 6,
        6, 3, 5, 8, 0, 0, 5, 2, 9, 4, 7, 1, 2, 3, 5, 9, 6, 4, 4, 3, 8, 6, 8, 3,
        5, 6, 3, 4, 9, 6, 1, 6, 8, 8, 4, 8, 7, 2, 2, 3, 4, 1, 7, 9, 7, 9, 2, 8,
        9, 4, 8, 7, 1, 1, 6, 1, 6, 2, 2, 4, 6, 9, 9, 4, 3, 0, 3, 3, 8, 7, 9, 2,
        5, 0, 3, 7])
tensor([8, 9, 4, 8, 2, 1, 7, 2, 6, 2, 2, 6, 6, 8, 7, 5, 3, 5, 7, 5, 8, 1, 0, 9,
        8, 2, 8, 8, 8, 8, 6, 3, 1, 1, 9, 6, 1, 7, 2, 8, 5, 1, 1, 1, 1, 7, 4, 0,
        6, 8, 1, 3, 5, 2, 5, 2, 8, 0, 2, 8, 8, 2, 2, 8, 4, 6, 3, 3, 7, 3, 1, 3,
        4, 6, 4, 7, 7, 6, 5, 3, 7, 8, 3, 8, 8, 2, 2, 6, 4, 1, 9, 7, 9, 4, 3, 4,
        0, 9, 6, 6])
tensor([1, 3, 1, 8, 1, 7, 6, 8, 7, 7, 8, 8, 4, 1, 7, 0, 3, 6, 2, 0, 1, 1, 3, 0,
        8, 5, 3, 0, 5, 4, 8, 3, 1, 0, 9, 5, 5, 6, 4, 8, 7, 0, 2, 0, 8, 0, 4, 7,
        1, 9, 4, 8, 2, 8, 0, 6, 6, 1, 1, 2, 0, 2, 8, 6, 9, 5, 8, 4, 8, 1, 4, 9,
        7, 3, 3, 2, 4, 1, 7, 6, 3, 7, 2, 5, 6, 3, 7, 5, 5, 8, 5, 4, 0, 1, 4, 3

        6, 5, 8, 2])
tensor([8, 7, 0, 4, 0, 4, 2, 5, 2, 4, 5, 6, 4, 6, 8, 4, 3, 8, 1, 4, 0, 5, 7, 7,
        9, 1, 1, 2, 5, 7, 3, 5, 2, 4, 8, 1, 8, 0, 9, 9, 2, 1, 9, 8, 4, 5, 4, 4,
        1, 9, 0, 5, 1, 6, 3, 1, 1, 0, 1, 5, 7, 8, 3, 8, 6, 5, 2, 4, 4, 5, 0, 9,
        5, 2, 3, 7, 1, 7, 9, 0, 1, 7, 8, 9, 1, 2, 5, 0, 0, 7, 9, 2, 3, 1, 9, 3,
        2, 6, 6, 6])
tensor([3, 1, 5, 4, 0, 5, 7, 9, 4, 8, 3, 9, 2, 8, 9, 0, 0, 8, 9, 8, 9, 6, 8, 4,
        2, 9, 9, 5, 0, 2, 0, 2, 0, 6, 7, 1, 9, 1, 0, 6, 5, 4, 4, 0, 4, 9, 4, 6,
        7, 2, 6, 0, 4, 9, 8, 7, 8, 7, 3, 8, 3, 8, 3, 7, 8, 9, 9, 6, 9, 1, 2, 8,
        1, 5, 3, 8, 2, 3, 1, 8, 4, 4, 7, 4, 0, 9, 1, 7, 6, 7, 8, 5, 1, 8, 2, 5,
        5, 3, 9, 4])
tensor([1, 0, 8, 9, 4, 6, 0, 2, 5, 3, 4, 1, 0, 0, 9, 4, 7, 5, 1, 2, 2, 6, 5, 6,
        6, 2, 3, 3, 6, 5, 2, 6, 8, 3, 0, 0, 3, 0, 3, 9, 0, 6, 1, 5, 9, 3, 5, 2,
        0, 0, 0, 1, 2, 2, 2, 3, 3, 7, 8, 5, 8, 5, 6, 4, 2, 7, 1, 3, 9, 2, 0, 8,
        3, 0, 2, 6, 9, 8, 9, 9, 6, 6, 5, 1, 3, 7, 9, 1, 8

        0, 1, 9, 9])
tensor([8, 0, 1, 9, 7, 4, 1, 1, 4, 6, 7, 4, 6, 7, 3, 7, 8, 0, 1, 3, 5, 2, 8, 6,
        4, 2, 1, 4, 7, 3, 0, 0, 5, 0, 1, 6, 9, 5, 3, 7, 6, 6, 4, 1, 8, 5, 4, 8,
        1, 5, 6, 0, 4, 4, 9, 6, 1, 9, 5, 3, 7, 2, 1, 5, 6, 3, 9, 2, 5, 9, 5, 0,
        4, 3, 3, 1, 5, 2, 1, 7, 9, 5, 7, 6, 4, 1, 3, 7, 0, 6, 4, 2, 3, 4, 8, 0,
        7, 2, 9, 8])
tensor([4, 8, 5, 7, 4, 0, 8, 8, 3, 4, 7, 0, 5, 8, 2, 6, 0, 7, 1, 2, 2, 2, 1, 5,
        8, 0, 4, 0, 5, 0, 7, 3, 8, 1, 3, 2, 3, 4, 6, 2, 3, 6, 8, 0, 9, 2, 9, 1,
        1, 8, 0, 7, 7, 0, 1, 4, 3, 9, 8, 9, 6, 7, 0, 9, 5, 2, 0, 1, 6, 8, 6, 5,
        2, 1, 1, 0, 8, 9, 4, 8, 9, 1, 2, 1, 1, 3, 2, 8, 0, 7, 0, 9, 9, 8, 6, 1,
        4, 0, 0, 6])
tensor([2, 1, 5, 0, 5, 3, 2, 6, 9, 0, 1, 1, 4, 0, 0, 6, 2, 4, 9, 5, 4, 6, 6, 3,
        0, 2, 4, 9, 3, 6, 0, 4, 3, 3, 4, 2, 8, 8, 7, 1, 4, 5, 0, 6, 2, 3, 6, 3,
        1, 7, 0, 4, 0, 9, 7, 7, 7, 1, 9, 1, 6, 6, 5, 6, 6, 0, 2, 3, 7, 8, 6, 1,
        9, 3, 8, 9, 6, 3, 5, 7, 4, 1, 6, 9, 7, 9, 0, 1, 6

tensor([9, 2, 6, 6, 1, 4, 0, 9, 6, 1, 9, 7, 4, 2, 5, 5, 8, 5, 2, 8, 4, 9, 2, 9,
        3, 5, 7, 1, 7, 0, 7, 6, 5, 8, 8, 6, 3, 2, 8, 7, 6, 0, 2, 8, 1, 6, 1, 0,
        9, 6, 1, 7, 0, 3, 1, 4, 7, 3, 3, 0, 6, 9, 6, 5, 6, 9, 5, 1, 4, 6, 2, 2,
        8, 6, 1, 0, 2, 0, 9, 1, 3, 1, 3, 6, 4, 0, 6, 2, 6, 6, 6, 9, 1, 1, 0, 9,
        8, 2, 6, 8])
tensor([6, 0, 2, 1, 3, 1, 0, 3, 5, 7, 8, 5, 4, 8, 9, 3, 0, 4, 0, 3, 3, 0, 7, 5,
        0, 9, 0, 9, 7, 9, 4, 0, 1, 5, 3, 1, 2, 9, 0, 9, 3, 7, 6, 3, 4, 1, 8, 9,
        9, 5, 5, 4, 7, 6, 1, 2, 1, 3, 4, 1, 6, 2, 8, 9, 7, 5, 8, 4, 6, 7, 8, 0,
        1, 9, 2, 3, 5, 0, 1, 9, 4, 9, 7, 7, 2, 6, 2, 1, 4, 6, 9, 4, 2, 9, 8, 3,
        2, 7, 7, 0])
tensor([9, 5, 0, 1, 3, 6, 0, 0, 5, 8, 8, 3, 7, 5, 2, 7, 7, 3, 4, 6, 5, 4, 1, 5,
        2, 9, 0, 8, 4, 2, 3, 2, 6, 1, 9, 1, 6, 2, 0, 6, 9, 7, 9, 6, 4, 4, 8, 9,
        1, 8, 7, 2, 7, 3, 9, 0, 4, 8, 3, 3, 0, 8, 7, 1, 2, 1, 5, 9, 8, 2, 3, 7,
        1, 7, 8, 6, 0, 8, 3, 0, 2, 8, 7, 7, 7, 5, 6, 3, 2, 4, 5, 7, 4, 1, 9, 7

tensor([2, 1, 3, 9, 6, 1, 0, 5, 6, 6, 2, 4, 3, 6, 2, 7, 3, 2, 5, 8, 8, 6, 5, 8,
        0, 2, 5, 7, 0, 3, 6, 7, 9, 2, 9, 0, 8, 1, 3, 2, 5, 9, 1, 7, 1, 3, 1, 6,
        7, 9, 0, 5, 2, 5, 3, 0, 5, 9, 3, 3, 3, 4, 3, 3, 6, 7, 6, 1, 9, 4, 6, 5,
        0, 7, 3, 2, 5, 1, 0, 1, 5, 9, 2, 7, 4, 6, 5, 5, 4, 0, 7, 3, 3, 6, 1, 0,
        9, 4, 6, 1])
tensor([6, 3, 3, 3, 1, 2, 4, 1, 0, 4, 8, 6, 4, 9, 1, 2, 5, 5, 0, 9, 2, 5, 0, 0,
        6, 0, 8, 9, 0, 4, 4, 6, 3, 0, 6, 9, 7, 6, 1, 2, 2, 2, 9, 9, 9, 4, 2, 1,
        6, 8, 1, 0, 1, 0, 4, 3, 7, 7, 8, 5, 3, 5, 2, 8, 4, 7, 0, 7, 9, 4, 3, 2,
        4, 7, 4, 4, 5, 1, 0, 0, 2, 3, 6, 0, 3, 4, 4, 1, 1, 8, 6, 8, 5, 1, 0, 7,
        5, 3, 4, 3])
tensor([2, 1, 7, 2, 6, 4, 0, 9, 4, 8, 1, 4, 4, 7, 8, 6, 2, 7, 2, 2, 7, 1, 7, 8,
        1, 7, 1, 7, 9, 9, 4, 3, 3, 4, 9, 9, 2, 3, 5, 3, 1, 5, 7, 5, 5, 7, 6, 4,
        9, 1, 9, 5, 0, 0, 1, 1, 1, 8, 6, 3, 3, 5, 7, 2, 2, 8, 0, 8, 6, 7, 0, 1,
        1, 5, 7, 2, 5, 4, 7, 1, 8, 9, 9, 0, 3, 6, 8, 6, 0, 4, 9, 6, 6, 3, 1, 4

        8, 1, 7, 1])
tensor([9, 6, 7, 4, 1, 0, 8, 2, 9, 4, 3, 8, 2, 4, 6, 2, 9, 0, 8, 0, 1, 4, 2, 4,
        0, 8, 1, 6, 2, 1, 1, 9, 0, 3, 9, 8, 7, 6, 4, 2, 8, 9, 1, 6, 0, 6, 6, 2,
        6, 6, 6, 9, 9, 3, 4, 3, 4, 3, 7, 4, 8, 8, 3, 2, 6, 9, 3, 4, 8, 4, 5, 0,
        6, 2, 8, 9, 1, 4, 0, 9, 9, 6, 8, 0, 4, 8, 4, 7, 7, 6, 9, 7, 3, 7, 5, 4,
        1, 6, 1, 0])
tensor([9, 3, 1, 8, 4, 0, 5, 5, 6, 2, 6, 5, 5, 0, 6, 2, 4, 1, 2, 0, 6, 2, 3, 2,
        2, 1, 0, 9, 0, 0, 3, 0, 4, 2, 8, 8, 3, 9, 3, 7, 9, 2, 4, 2, 4, 6, 8, 1,
        7, 7, 9, 5, 6, 2, 8, 8, 8, 5, 6, 5, 9, 2, 2, 2, 5, 9, 7, 1, 7, 0, 9, 0,
        6, 0, 4, 1, 4, 7, 5, 0, 8, 9, 4, 6, 7, 0, 4, 3, 5, 4, 8, 8, 8, 9, 5, 2,
        9, 4, 7, 6])
tensor([3, 7, 2, 2, 8, 3, 3, 1, 4, 2, 0, 8, 5, 0, 3, 1, 3, 2, 4, 1, 5, 1, 1, 3,
        6, 7, 6, 7, 7, 0, 5, 7, 5, 7, 9, 5, 5, 2, 0, 2, 3, 9, 7, 1, 7, 1, 1, 3,
        1, 0, 7, 2, 6, 6, 0, 3, 8, 3, 6, 7, 5, 6, 1, 6, 0, 3, 8, 9, 8, 4, 2, 1,
        2, 5, 7, 5, 4, 2, 4, 4, 7, 6, 6, 2, 8, 5, 3, 0, 3

In [97]:
#### Train Model

iter = 0
for epoch in range(num_epochs):
    for i,(images,labels) in enumerate(train_loader):
        
        #Load images as Variable
        images = Variable(images.cuda())
        labels = Variable(labels.cuda())
        
        #Clear gradients w.r.t. parameters
        optimizer.zero_grad()
        
        #Forward pass to get output/logits
        outputs=model(images)
        
        #Calculate Loss: Softmax -->cross entropy loss
        loss = criterion(outputs,labels)
        
        #Getting gradients w.r.t. parameters
        loss.backward()
        
        #Updating the parameters
        optimizer.step()
        
        iter+=1
        
        if iter%500==0:
            #Calculate accuracy
            correct = 0
            total = 0
            
            #Iterate through entire dataset
            for images,labels in test_loader:
                
                #Load images to a Torch Variable
                images = Variable(images.cuda())
                
                #Forward pass only to get logits/output
                outputs = model(images)
                
                #Get predictions from the maximum value
                _,predicted = torch.max(outputs.data,1)
                
                #Total number of labels 
                total+=labels.size(0)
                
                #Total correct predictions
                correct += (predicted.cpu()==labels.cpu()).sum()
            
            accuracy = 100 * correct/total
            
            #Print loss
            print('Iteration: {}, Loss: {}, Accuracy: {}'.format(iter,loss.data,accuracy))
            

Iteration: 500, Loss: 0.5131245851516724, Accuracy: 89
Iteration: 1000, Loss: 0.20818428695201874, Accuracy: 92
Iteration: 1500, Loss: 0.15619687736034393, Accuracy: 94
Iteration: 2000, Loss: 0.17398256063461304, Accuracy: 95
Iteration: 2500, Loss: 0.15125831961631775, Accuracy: 96
Iteration: 3000, Loss: 0.09744241833686829, Accuracy: 96
